### ISSUE TITLE
请问支持模拟器吗

### ISSUE THREAD

**Issue by laihanhua** [AirtestProject/Poco#103]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

请问支持模拟器吗？如mumu模拟器。我使用mumu模拟器只能打开应用，后续就没反应了，使用真机的话可以正常进行测试。

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by adolli** [comment]
我试过支持MuMu和夜神，别的我没测试过不太确定。
