### ISSUE TITLE
poco在android上是否支持xpath定位？

### ISSUE THREAD

**Issue by shenghe1027** [AirtestProject/Poco#104]
测试的时候APP的id进行了混淆，同一个应用，换一个安装包脚本就无法执行。能否支持xpath定位，提高稳定性？

**Comment by adolli** [comment]
不支持xpath的语法，但是可以实现一样的效果，给你个例子。  
例如某个UI的xpath为: `/root/layer[className~=main.*$]//panel/button[type=Button][text=done]`
```py
poco = ...
ui = (poco('root')
    .child('layer', classNameMatches='main.*$')
    .offspring(panel)
    .child(button, type='Button', text='done'))
ui.get_text()
ui.click()
...
```
更多poco语法请见README或文档
