### ISSUE TITLE
点击时出现报错poco.utils.simplerpc.simplerpc.RpcTimeoutError

### ISSUE THREAD

**Issue by yuantianshi** [AirtestProject/Poco#107]
**描述问题bug**
用的apk是cocos2dx引擎，用airtest ide运行poco().click()，log窗口显示运行到[rpc]connected，运行了很久，然后出现了一个报错（如图），游戏是已经打开的

![image](https://user-images.githubusercontent.com/45068216/48554400-42dc7b00-e919-11e8-8d3f-bdd8c47c7531.png)

**python 版本:** `python3.6.5`

**ide版本:** `1.1.0`
python、poco都是自带的版本

**设备:**
海马玩模拟器

**其他相关环境信息**
windows
cocos2dx版本是3.4

我看到别人提的issue，unity有遇到一个类似的问题，说是更新sdk修复了，不知道cocos有没有修复呢？issue链接如下：
https://github.com/AirtestProject/AirtestIDE/issues/58

**Comment by adolli** [comment]
这个跟unity应该不是同一个问题。你能看到游戏那边的log有没有提示pocosdk断开或者别的报错信息吗？

**Comment by yuantianshi** [comment]
游戏那边显示 [poco] new client accepted  127.0.0.1，然后等待了好久，提示[poco] client  disconnect

**Comment by adolli** [comment]
IDE里能看到正常的UI树吗？

**Comment by yuantianshi** [comment]
可以看到 @adolli

**Comment by yuantianshi** [comment]
.........又可以了，我重启airtest，连了下手机试了下就好了，再开模拟器也可以 了.......真是麻烦您了-。-
