### ISSUE TITLE
测试用例 方案投票 [[[ Click Me! How to write testcase voting ]]]

### ISSUE THREAD

**Issue by adolli** [AirtestProject/Poco#11]
airtest和poco提供两种编写测试用例的方案，该投票想了解一下大家对测试用例编写、运行等需求，以便我们确定重点开发方向。两种方案我们的框架都是兼容的，不用担心以后不支持的问题。

1. **test.air/**: 使用.air的目录组织测试用例，一个.air对应一个用例
1. **python库**: 按照标准的python库去组织所有用例，整个库包含项目所有的用例

请在下面两层楼的大拇指上投票，👍或者👎。 有想法或建议请跟楼评论

**Comment by adolli** [comment]
## test.air/

好处：
* 结构简单，AirtestIDE开箱即用
* 只需了解最基本的python语法，非常容易上手

坏处：
* 不能满足众多用例的管理
* 运行结果展示细节有限

**Comment by adolli** [comment]
## python库 [my-testflow](https://github.com/AirtestProject/my-testflow)

好处：
* 能够应对各种复杂的测试场景和需求
* 配套工具丰富，pycharm可以自动补全代码，[TestResultPlayer](http://poco.readthedocs.io/en/latest/source/doc/about-test-result-player.html)可以展示丰富详细的运行结果

坏处：
* 需要比较熟练掌握python
* 不能使用AirtestIDE辅助截图和设备操作，需要使用[HierarchyViewer](http://poco.readthedocs.io/en/latest/source/doc/about-standalone-inspector.html)、[TestResultPlayer](http://poco.readthedocs.io/en/latest/source/doc/about-test-result-player.html)等工具完成编写和调试
* 使用文本编辑器编写代码(pycharm, sublime, ...)

**Comment by adolli** [comment]
方案2的可以先clone一个[my-testflow](https://github.com/AirtestProject/my-testflow)来试一下效果

**Comment by XedGo** [comment]
我自己弄了一个框架，没用testflow，感觉不怎么完善。现在可以直接用IDE调试好，然后把代码放到我的框架里跑
