### ISSUE TITLE
poco无法在oppo手机启动

### ISSUE THREAD

**Issue by FuckyouBB** [AirtestProject/Poco#116]
**描述问题bug**
oppo 手机 启动poco失败，各类自动安装的app都装上了，然后一直显示still waiting for uiautomation ready.，用例无法执行下去

```
RuntimeError: unable to launch AndroidUiautomationPoco
```

**复现步骤**
启动用例，在poco初始化语句失败

**python 版本:** `python3.5`

**poco 版本:** `1.0.70`

**设备:**
 - 型号: OPPO A57 R9s
 - 系统:  Android 6.0

Window，华为手机 可以运行

**Comment by yimelia** [comment]
请参考 [文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#oppo) ，如果还是不行，请贴出完整的报错内容

**Comment by FuckyouBB** [comment]
之前 发现了，手机上 装了 uiautomator2 来远程连接， 把这个关掉就 可以正常连接
