### ISSUE TITLE
请教一下在移动设备android 或者 ios上有命令能获取已加载过的元素吗

### ISSUE THREAD

**Issue by magickilig** [AirtestProject/Poco#121]
比如下图中我想获取全部的列表页
![qq 20181227172147](https://user-images.githubusercontent.com/26734950/50474448-e8483b80-09fb-11e9-86cb-825db19780b8.jpg)

**Comment by yimelia** [comment]
应该没有。
目前你的描述不是非常清晰，建议更加清晰地描述清楚问题。这个Issue我先关闭了。
