### ISSUE TITLE
TextMeshProUGUI的文本无法获取到

### ISSUE THREAD

**Issue by PitayaDEV** [AirtestProject/Poco#123]
**你遇到了什么我们这个库解决不了的问题？**
使用了TextMeshProUGUI来展示文本，在Poco中获取不到文本的值。

属性查看器里只能查看到以下信息。
Path from root node: [0, 3, 7, 1, 1, 2, 1]
Payload details:
	  type :  Node 
	  name :  Text 
	  visible :  True 
	  pos :  [0.855432153, 0.025] 
	  size :  [0.127777785, 0.027777778] 
	  scale :  [1.0, 1.0] 
	  anchorPoint :  [0.5, 0.5] 
	  zOrders :  {'global': 0.0, 'local': 0.0} 
	  clickable :  False 
	  components :  ['RectTransform', 'CanvasRenderer', 'TextMeshProUGUI'] 
	  _ilayer :  5 
	  layer :  b'UI' 
	  _instanceId :  -2352

**Comment by rockywhisper** [comment]
@PitayaDEV  
您好，很抱歉，poco暂时确实没有解析文本信息这一项，请问在实际中是否确实有文本解析需求？

对于通用类的需求，我们可以考虑增加对应的信息条目，如确实有这种需求，请尽快回复，感谢。   :-)

**Comment by startnothings** [comment]
我有这种需求，嘿嘿

**Comment by adolli** [comment]
@PitayaDEV 请问TextMeshProUGUI在Unity API里是否有提供获取文本的方法？如果有的话是可以有办法获取文本的值。

**Comment by Noxalus** [comment]
Hello everyone, 

I also need this as image comparison is too long for my test case!

**Comment by dys862415** [comment]
@adolli 这个问题有排期嘛 很是需要呀

**Comment by jilvtianya** [comment]
https://github.com/AirtestProject/Poco/issues/324#issuecomment-566350763

**Comment by chenchusheng** [comment]
求加，这边也有需求，获取不到
