### ISSUE TITLE
使用unittest模块并且使用HTMLtestrunner生成报告，结果报告内容为空

### ISSUE THREAD

**Issue by thisluren** [AirtestProject/Poco#130]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
用unittest做测试用例编辑，最后用HTMLtestrunner生成报告后，打开报告内容为空

```
（在这里粘贴traceback或其他报错信息）
```

**预期效果**
完成用例后，报告有内容

**相关截图**
![image](https://user-images.githubusercontent.com/46642615/51082709-b4814b80-1747-11e9-8c0d-7f725595eee5.png)

**python 版本:** `python3.7`

**poco 版本:** `1.0.71`
> poco版本通过`pip freeze`可以命令可以查到

**其他相关环境信息**
windows运行，编辑器pycharm

**Comment by rockywhisper** [comment]
@thisluren 
你好，airtest的内嵌unittest用法与正常的Unittest用法完全不同，可能运行时并没有正确运行到脚本，以及报告的生成也是[独立的指令](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id12)，可能无法简单与现有unittest专用框架直接融合，建议根据实际情况另外进行代码编写。
