### ISSUE TITLE
怎么样集成Cocos Creator项目? (How to integrate with cocos creator project?)

### ISSUE THREAD

**Issue by developerworks** [AirtestProject/Poco#14]
http://poco.readthedocs.io/en/latest/source/doc/integration.html#cocos2dx-js-beta

**Comment by Meteorix** [comment]
你好，我们测试过cocos creator项目，也是可以的。在你生成了项目后，需要手动操作项目里面的一些文件，中文文档参考这里：

http://poco-chinese.readthedocs.io/zh_CN/latest/source/doc/integration.html#cocos2dx-js-beta

**Comment by dengxue0** [comment]
@adolli 第4步需要做吗，项目中并没有AppDelegate.cpp这个文件，把poco文件夹拷贝到项目脚本目录，启动时报错，sdk/AbstractDumper.js 如何放到 Cocos2dxDumper.js 之前加载
