### ISSUE TITLE
long_click事件无效

### ISSUE THREAD

**Issue by sunhailin-Leo** [AirtestProject/Poco#140]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
没有报错，就是长按事件无效
在用 Airtest IDE 跑的时候就可以，但是在 Pycharm 中运行代码，就无法生效 

**复现步骤**
无

**预期效果**
出现粘贴按钮

**相关截图**
无

**python 版本:** `python3.7`

**poco 版本:** `1.0.75`

**设备:**
 - 型号: [ZTEBA520]
 - 系统: [Android 6.0]

**Comment by sunhailin-Leo** [comment]
* 场景描述: 编辑短信接受者，将联系人的姓名长按粘贴进去(名字确认已成功复制)

* 目前进度: 自己解决了这个问题

* 解决方案:
```python
from airtest.core.android.minitouch import Minitouch

# device_1 是自己的设备从 Airtest 的 connect_device 中初始化
# tuple_xi 则是输入框的坐标

mini_touch = Minitouch(adb=device_1.adb)
mini_touch.touch(tuple_xy=(316, 199), duration=3.0)
```

**Comment by loneyao** [comment]
> * 场景描述: 编辑短信接受者，将联系人的姓名长按粘贴进去(名字确认已成功复制)
> * 目前进度: 自己解决了这个问题
> * 解决方案:
> 
> ```python
> from airtest.core.android.minitouch import Minitouch
> 
> # device_1 是自己的设备从 Airtest 的 connect_device 中初始化
> # tuple_xi 则是输入框的坐标
> 
> mini_touch = Minitouch(adb=device_1.adb)
> mini_touch.touch(tuple_xy=(316, 199), duration=3.0)
> ```

请问支持原生安卓操作吗？

**Comment by yimelia** [comment]
初始化poco时，在参数中指定用airtest的方式来操作，use_airtest_input=True：
```
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
```
然后就可以long_click了
```
poco("xxx").long_click()
poco("xxx").long_click(duration=3)
```
如果还是不行，可以直接用airtest来点击就行了
touch((x, y), duration=3)

所有操作都需要初始化安卓设备时用了默认的touch_method，也就是说如果是命令行运行的话，`--device Android:///设备号`后面不带touch_method参数，如果设备是在脚本里初始化的（比如用connect_device来连接），不要指定touch_method，才会默认使用Minitouch点击。

所以正常情况下，其实是没必要手工初始化Minitouch再点的，直接用airtest的touch接口点就行了。
