### ISSUE TITLE
批量执行过程中出现retrying instrumentation PocoService错误，一直持续不停打印这个错误日志（高概率偶现）

### ISSUE THREAD

**Issue by baobao01test** [AirtestProject/Poco#141]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
批量执行脚本，后台日志一直打印retrying instrumentation PocoService错误，前台界面等待很长时间后会正确执行

（在这里粘贴traceback或其他报错信息）
后台一直打印retrying instrumentation PocoService错误，具体错误信息请看截图

**复现步骤**
批量执行多个脚本文件的时候，在不同脚本不同代码偶现

**预期效果**
执行后台不报错误

**相关截图**
![image](https://user-images.githubusercontent.com/47881818/53380997-436dbe80-39aa-11e9-8f23-f2d6b0a665f1.png)

**python 版本:** `Python 3.4.3`

**poco 版本:** `1.0.70`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [荣耀9青春版]
 - 系统: [安卓8.0]
 - (别的信息)

**其他相关环境信息**
批量执行多个脚本时高概率偶现

**Comment by StevenXUzw** [comment]
升级pocoui版本到最新即可，1.0.76
