### ISSUE TITLE
请问Poco是基于UiAutomator 1.x还是 2.x

### ISSUE THREAD

**Issue by JustinToken** [AirtestProject/Poco#146]
**你遇到了什么我们这个库解决不了的问题？**
POCO service 频繁出现Process crashed。根本无法多设备并发群控。

**描述一下你想如何解决这个问题**
我想知道 POCO基于什么框架。我想引入其他框架 如appium来解决问题。

**额外信息**
python 3.7 安卓8.1 nova3i

**Comment by yuzhujiutian** [comment]
你那边后来是怎么解决的？

下面也有同类问题现象反馈，但暂时没有找到原因。

[airtestIDEv1.2.1中选择poco Android后pocoservice就会频繁重启 #384](https://github.com/AirtestProject/Airtest/issues/384)
