### ISSUE TITLE
我用mac连接ios设备，使用airtest ide。poco切到ios之后，识别不了ios的原生控件.poco基本不能用

### ISSUE THREAD

**Issue by tommyshen123** [AirtestProject/Poco#148]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**问题分类**：
控件识别、树状结构、poco库报错

**描述问题bug**
使用mac连接ios设备，使用airtest IDE。 切换poco到ios后，识别不了树状结构。
mac os  10.13.6
xcode: 10.1(10B61)

**复现步骤**
1. 布署 iOS-Tagent
2. 运行xcode. iproxy 8100 8100
3. 启动ide，连接设备
4. poco界面切到ios

**预期效果**
可以显示UI树分票

**相关截图**
显示不出树分枝
![image](https://user-images.githubusercontent.com/48204584/53726752-9f07e280-3ea9-11e9-948e-c6a560189b59.png)

**python 版本:** `python 2.7.15`

**poco 版本:** `1.0.75`

**设备:**
 - 型号: [MacBook Pro]
 - 系统: [mac 10.13.6]
 - airtest 版本: 1.2.0 (mac)
 - xcode 版本: 10.1(10B61)

**其他相关环境信息**
有配过appium的环境，，但是应该不是这个原因造成。急求解决，，谢谢啦。。我qq553029597

**Comment by yimelia** [comment]
看到有报错信息，可以用[命令行方式](http://airtest.netease.com/docs/cn/9_faq/1_ide_crash.html#id2)来启动IDE，截到报错log发上来看看

**Comment by tommyshen123** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/48204584/53802972-39395a80-3f7e-11e9-88e7-59b2493e4580.png">
已上传，，麻烦看看呢？感觉像是没识别到我的ios设备窗口

**Comment by tommyshen123** [comment]
在吗， @yimelia    能帮忙看下吗？

**Comment by EraChen233** [comment]
@tommyshen123 
你可以试试在浏览器访问iproxy地址，默认是127.0.0.1:8100/inspect，有什么输出信息？

**Comment by tommyshen123** [comment]
{
  "value" : "Unhandled endpoint: \/inspect -- http:\/\/127.0.0.1:8100\/ with parameters {\n    wildcards =     (\n        inspect\n    );\n}",
  "sessionId" : "EA7C894D-56C0-446D-90CD-43B48965C8C4",
  "status" : 1
}

**Comment by tommyshen123** [comment]
没识别到是吧？@EraChen233

**Comment by tommyshen123** [comment]
另外我xcode也有报红色的，会不会是这个造成的。。我是萌新，，不知道怎么解决
<img width="308" alt="image" src="https://user-images.githubusercontent.com/48204584/53947223-4da56080-4100-11e9-9e3c-06e6a883e865.png">

**Comment by EraChen233** [comment]
xcode 具体的报错信息可以贴一下吗？你截图的标红色部分

**Comment by tommyshen123** [comment]
实际上xcode能跑起来，也没报错信息。那个红色的刚刚问了下开发是某些文件不在。不影响的。

**Comment by EraChen233** [comment]
那现在问题还存在么？

**Comment by tommyshen123** [comment]
还是有这个问题，，airtrest ide里面poco不能用。。。mac

**Comment by EraChen233** [comment]
连接好设备之后，你试试在浏览器打开地址，看是否能看到手机页面，点击刷新按钮是否能成功
http://127.0.0.1:8100/inspector
之前地址写错

**Comment by tommyshen123** [comment]
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/48204584/54013609-bfd77d00-41b4-11e9-9c43-b80b224aa1e1.png">
已上传，请看一下呢？   感觉我点击的坐标和实际的UI对应不上。我点击的时候识别到我手机背景上了

**Comment by brantxiong** [comment]
@tommyshen123 需要用我们的iOS-tagent项目启动才行：https://github.com/AirtestProject/iOS-Tagent

**Comment by tommyshen123** [comment]
@brantxiong 我是照着那个文档一步一步配的呀，

**Comment by brantxiong** [comment]
> 另外我xcode也有报红色的，会不会是这个造成的。。我是萌新，，不知道怎么解决
> <img alt="image" width="308" src="https://user-images.githubusercontent.com/48204584/53947223-4da56080-4100-11e9-9e3c-06e6a883e865.png">

看这个截图，好像不是iOS-Tagent项目。

**Comment by tommyshen123** [comment]
原来如此。。我大概明白是哪个地方的问题了。。。。晚点我试一试，，稍后答复你。
