### ISSUE TITLE
poco service中途挂掉无法重启，程序跑飞

### ISSUE THREAD

**Issue by StevenXUzw** [AirtestProject/Poco#149]
/Users/***/Library/Python/3.7/lib/python/site-packages/poco/drivers/android/uiautomation.py:278: UserWarning: [pocoservice.apk] instrumentation test server process is no longer alive
  warnings.warn("[pocoservice.apk] instrumentation test server process is no longer alive")

**Comment by StevenXUzw** [comment]
1.0.75版本新增的，一直循环在打印，程序没结束
class KeepRunningInstrumentationThread(threading.Thread):
    """Thread class with a stop() method. The thread itself has to check
    regularly for the stopped() condition."""

    def __init__(self, poco, port_to_ping):
        super(KeepRunningInstrumentationThread, self).__init__()
        self._stop_event = threading.Event()
        self.poco = poco
        self.port_to_ping = port_to_ping

    def stop(self):
        self._stop_event.set()

    def stopped(self):
        return self._stop_event.is_set()

    def run(self):
        while not self.stopped():
            if getattr(self.poco, "_instrument_proc", None) is not None:
                stdout, stderr = self.poco._instrument_proc.communicate()
                print('[pocoservice.apk] stdout: {}'.format(stdout))
                print('[pocoservice.apk] stderr: {}'.format(stderr))
            if not self.stopped():
                print('[pocoservice.apk] retrying instrumentation PocoService')
                self.poco._start_instrument(self.port_to_ping)  # å°è¯éå¯
                time.sleep(1)

**Comment by yimelia** [comment]
更新到最新版本即可解决此问题

**Comment by 1158536658** [comment]
更新了最新的还是这样
