### ISSUE TITLE
小米8手机无法正常运行poco

### ISSUE THREAD

**Issue by chengpeixin** [AirtestProject/Poco#150]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
我是用usb的方式连接手机，使用poco库选择控件点击，在click事件触发时报错
使用截图方式的touch可以正常打开
```
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "name=美团"
```

**复现步骤**
1. 我使用usb方式连接小米手机
2. poco('text=美团').click()
3. 报错
4. 报错信息为
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "name=美团"

**预期效果**
预期可以正常打开美团APP

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python3.6`

**poco 版本:** `1.0.75`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: 小米8
 - 系统: Android 9.0
 - (别的信息)

**其他相关环境信息**
环境是windows 10系统

**Comment by chengpeixin** [comment]
![1551755931 1](https://user-images.githubusercontent.com/28584833/53778836-1df82c00-3f39-11e9-884f-b56b8fb13c94.jpg)

**Comment by chengpeixin** [comment]
![1551756338 1](https://user-images.githubusercontent.com/28584833/53778954-7af3e200-3f39-11e9-8f3f-1f77eac3b44d.jpg)

**Comment by yimelia** [comment]
poco的语句编写方法请参考[文档](https://poco.readthedocs.io/zh_CN/latest/source/README.html#working-with-poco-objects)。
可以直接用IDE生成的语句来修改，双击节点可以自动生成语句。
可能是你的poco节点写错了，试一下poco('美团')

**Comment by chengpeixin** [comment]
谢谢
