### ISSUE TITLE
poco(text="")失效

### ISSUE THREAD

**Issue by kongguliu** [AirtestProject/Poco#157]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
根据官网游戏测试的教程，一样的代码，但是poco(text="")失效。测试官网的tutorial是可以的，但是测试自己开发的两个应用不行

```
（在这里粘贴traceback或其他报错信息）
```

**复现步骤**

**预期效果**
能运行poco(text="")代码

**相关截图**
![image](https://user-images.githubusercontent.com/18191658/54181227-cded0c80-44d8-11e9-8d0f-c5f20d40cab1.png)
![image](https://user-images.githubusercontent.com/18191658/54181233-d47b8400-44d8-11e9-841b-1e39cb3d20dc.png)
![image](https://user-images.githubusercontent.com/18191658/54181244-e2310980-44d8-11e9-8355-b13fe0d61ec6.png)

**python 版本:** `python

**poco 版本:** 官网最新IDE
> poco版本通过`pip freeze`可以命令可以查到

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
可以使用IDE上的Poco相关功能，框选住你要的UI节点，找到对应节点后可以在UI树上双击节点来自动生成代码。
可以先选中这个茶园节点后截个图给我们看看，确认text=“茶园”真的能对应上这个节点。

**Comment by kongguliu** [comment]
> 可以使用IDE上的Poco相关功能，框选住你要的UI节点，找到对应节点后可以在UI树上双击节点来自动生成代码。
> 可以先选中这个茶园节点后截个图给我们看看，确认text=“茶园”真的能对应上这个节点。
![image](https://user-images.githubusercontent.com/18191658/54186059-72754b80-44e5-11e9-9def-8c41f31a8fa5.png)

**Comment by yimelia** [comment]
这个按钮的属性里可能没有茶园这个文字，不熟悉poco的情况下直接手写代码可能正确率很低，可以尝试直接用名字来选取 `poco("Btn_point1")` ，或者是直接双击你选中的这个节点，会自动帮你生成代码的。

**Comment by adolli** [comment]
茶园这几个字像是图片渲染的，不是文本
