### ISSUE TITLE
Any plan to open source the PocoHierarchyViewer?

### ISSUE THREAD

**Issue by yuewah** [AirtestProject/Poco#161]
Any plan to open source the PocoHierarchyViewer?

**Comment by adolli** [comment]
The viewer is just a few js codes. I will give u a reply after I talk to my team

**Comment by adolli** [comment]
Good news! Hierarchy viewer is now open-sourced. Check out this project at https://github.com/AirtestProject/PocoHierarchyViewer . The first-run installation will be a little bit longer, be patient.

**Comment by yuewah** [comment]
Thank a lot
