### ISSUE TITLE
刘海屏poco坐标计算偏移问题

### ISSUE THREAD

**Issue by magicedy** [AirtestProject/Poco#163]
**描述问题bug**
刘海屏的手机使用poco时，操作会有偏移，特别是没有完全适配刘海屏的app

![image](https://user-images.githubusercontent.com/23083411/54615063-674b8e00-4a98-11e9-87a9-ca5f844d653f.png)

poco的百分比坐标是poco-sdk中根据app的显示分辨率算出来的，但是最后操作(例如AirtestInput中的click)的时候换算回屏幕绝对坐标时，却用屏幕显示分辨率去计算，有刘海的屏幕这两个分辨率是不一样的，会造成偏差

```

class AirtestInput(InputInterface):
    def _get_touch_resolution(self):
        """
        get real time resolution on device if full screen
         or window size if running in window mode
        """
        return current_device().get_current_resolution()

    def click(self, x, y):
        pw, ph = self._get_touch_resolution()
        pos = [x * pw, y * ph]
        touch(pos, duration=self.default_touch_down_duration)
```

**设备:**
 - 型号: 华为nova 3

**Comment by yimelia** [comment]
非常感谢，我们会想办法适配一下这个问题

**Comment by magicedy** [comment]
1.0.77已修正，调用poco.use_render_resolution()即可
