### ISSUE TITLE
由子元素选择父元素

### ISSUE THREAD

**Issue by jekiki** [AirtestProject/Poco#168]
**你遇到了什么我们这个库解决不了的问题？**

+ 在poco选择树中，回溯其父元素

**描述一下你想如何解决这个问题**

+ poco中只能寻找兄弟元素，子元素和后代元素，但是无法寻找其父元素，祖先元素。

+ 拿到父元素就可以直接遍历其兄弟元素，怎么直接获取其兄弟元素的列表

+ 如何在poco中获取path from root
  -  Path from root node: [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0]
+ 如果可以通过path from root 定位元素的话，可以直接定位到指定祖先元素

**Comment by yimelia** [comment]
duplicate of #27
