### ISSUE TITLE
请问下UIObjectProxy有方法可以更新自己么？

### ISSUE THREAD

**Issue by stcnchenxin** [AirtestProject/Poco#17]
比如这种使用环境：
界面上存在2个同样名字的ui，然后迭代这2个ui，第一次循环会对第1个ui进行点击，但是会导致第2个ui的位置发生变化，在第2次循环的时候就会点到第2个ui老的位置了（而不是我想要的变化后的位置）。

有没有方法能类似下面这样操作：
```
for ui in poco('name'):
    ui.update()  #是否存在某个方法能直接更新自己，保证点到的都是最新的位置？
    ui.click()  #这个操作会导致下一个要点击的ui元素的对象发生变化
```

**Comment by adolli** [comment]
调用`ui.invalidate()`即可，下次click时会重新计算一次坐标。

**Comment by stcnchenxin** [comment]
可以了，多谢~

**Comment by adolli** [comment]
由于目前使用的是快照策略，如果在本轮for循环中，有ui消失或者有新的ui出现，invalidate后可能会造成ui错位，即本来已经访问到了第4个，即将访问第5个时，第1个ui滚出了屏幕，则第5个会变成第4个，顺次往前挪一个，继续访问第5个的话实际上访问到的是第6个。如果出现这种情况，请在测试逻辑里记录已访问的ui信息，或者等未来推出的非快照策略。
