### ISSUE TITLE
android poco 后台冻结

### ISSUE THREAD

**Issue by xvipservice** [AirtestProject/Poco#172]
![image](https://user-images.githubusercontent.com/1542619/55164692-15e18400-51a7-11e9-934c-1541365c30db.png)

**Comment by yimelia** [comment]
能否描述清楚你遇到的问题？

**Comment by xvipservice** [comment]
日志里写了，pocoservice被冻结了，然后测试脚本就卡在那了，不动了。

**Comment by xvipservice** [comment]
这个日志是andorid logcat里面的日志

**Comment by adolli** [comment]
这个需要在系统设置里设置一下允许pocoservice后台运行，可能在vivo自己的设置里可以调，也可能在开发者选项里设置后台应用程序限制策略。不然的话是跑不了测试脚本的。

**Comment by xvipservice** [comment]
任何设置都没有用，依然会被杀。

**Comment by xvipservice** [comment]
所以我修改了源码，启动pocoservice的时候不要弹出界面在回退，无界面启动，然后定时重启pocoserviec，用于解决这个问题
