### ISSUE TITLE
请问poco().exists()要怎么取反，想要写一个判断不存在的语句，但是!poco().exists()会报错

### ISSUE THREAD

**Issue by dengyanping** [AirtestProject/Poco#174]
**你遇到了什么我们这个库解决不了的问题？**
(尽量清晰描述你想解决什么问题，具体需求是怎么样的，要达到怎么样的效果。这样我们会更容易理解你所想要的东西。)

**描述一下你想如何解决这个问题**
(如果你有想法的话，不要犹豫，请告诉我们。)

**额外信息**
(运行环境、设备、相关参考信息，如果有的话。)

**Comment by adolli** [comment]
这个是python语法的问题

**Comment by xvipservice** [comment]
大哥 写not poco().exists() 啊

**Comment by dengyanping** [comment]
谢谢，已经解决了，之前用惯叹号取反，但是百度Python取反都是说!或者～取反，翻了好久才找到一个if not

**Comment by dengyanping** [comment]
谢谢，已经解决了，之前用惯叹号取反，但是百度Python取反都是说!或者～取反，翻了好久才找到一个用not的

**Comment by jekiki** [comment]
用 not and or 代替！ &&  ||，！ &&  ||不是python语法
