### ISSUE TITLE
Poco定位偏移(Std-broker)

### ISSUE THREAD

**Issue by ywhxauat** [AirtestProject/Poco#177]
**Poco定位偏移(Std-broker)**

**复现步骤**
1. 浏览器打开页面
2. 在cmd窗口连接代理python -m poco.utils.net.stdbroker ws://*:5003 tcp://*:15004
3. 打开Airtest IDE并选择Poco(Std-broke)
4. UI渲染树中元素定位偏移，如附件所示

**预期效果**
UI渲染树定位准确，无偏移

**相关截图**
![image](https://user-images.githubusercontent.com/49389360/55706530-ff8fbf80-5a13-11e9-8993-9895d924cd27.png)

**python 版本:** `python3.6.5`

**poco 版本:** `0.96.5`
**pocoui 版本:** `1.0.69`

**设备:**
 - Chrome 73.0.3683.75
 - 系统: win7 64位

**Comment by ywhxauat** [comment]
麻烦给下参考意见：这个是Poco本身存在的问题？还是接入Poco有问题？
期待大神回复......

**Comment by ywhxauat** [comment]
这个便宜程度和屏幕分辨率有关，如果是全屏会偏少一点
                                                       如果缩小窗口大小，会偏多

**Comment by rockywhisper** [comment]
@ywhxauat 
Hi，你好。

可以在连接windows窗口后，在设置窗口内的‘Windows Content Area Rect’选中一下窗口有效内容：
![image](https://user-images.githubusercontent.com/8188879/55937338-50e5bc00-5c6b-11e9-976a-3091e46f3e52.png)

poco实际上提供出来的UI数据，也是基于游戏画面的区域来的。你在IDE内完成设置后，IDE就会知道真正游戏画面的区域在哪里，从而可以渲染出正确的位置来。

**Comment by ywhxauat** [comment]
这样是有用的，偏移小了点，那么问题来了，我用脚本怎么控制Windows Content Area Rect呢？
求大神不吝赐教

**Comment by ywhxauat** [comment]
大神，有什么好的方法在代码中控制Windows Content Area Rect？

**Comment by ywhxauat** [comment]
@rockywhisper 有没有办法在代码中设置？

**Comment by rockywhisper** [comment]
@ywhxauat 
Hi，你好。

请在脚本中连接设备后加一行：
``` python
# focus_rect：[左边框宽度，上边框宽度，右边框宽度，下边框宽度]
device().focus_rect =  [int, int, int, int]
```
上面代码中设置的数值，是整个连接的窗口与有效画面之间的边框宽度。

**Comment by Caoruiqi** [comment]
您好，如果是手机的app，用std-broker起的poco，屏幕左边会因为躲避前置摄像头，实际画面会整体右移一小部分，这种因素导致的poco定位偏移应该怎么校正呢~求大佬们解答~蟹蟹
