### ISSUE TITLE
Poco辅助窗“定位”和“录制”功能无法使用

### ISSUE THREAD

**Issue by ywhxauat** [AirtestProject/Poco#178]
**Poco辅助窗“定位”和“录制”功能无法使用**

**复现步骤**
1. 打开游戏demo
2. 选择Unity
3. 点击“定位”，点击页面某一元素
4. 点击“录制”，做操作

**预期效果**
3. UI渲染树自动定位到被点击的元素
4. 录制代码成功生成

**实际效果**
3. UI渲染树未自动定位到被点击的元素
4. 无录制代码生成

**相关截图**
![image](https://user-images.githubusercontent.com/49389360/55707728-dde40780-5a16-11e9-8487-497b7fb56015.png)

python 版本: python3.6.5

poco 版本: 0.96.5
pocoui 版本: 1.0.69

设备:
Chrome 73.0.3683.75
系统: win7 64位

**Comment by ywhxauat** [comment]
我在官网查看教程，下载相应教学demo游戏
Airtest IDE中Poco 定位和录制功能无法使用
求大神指导下问题可能出现在哪里？

**Comment by ywhxauat** [comment]
我下载过不同版本的Airtest IDE，都不起作用，急求大神回复

**Comment by yimelia** [comment]
unity打包成的windows exe，在当前版本可能无法顺利进行录制。
官网视频上面的，是在Unity编辑器里将游戏窗口拖动出来，再嵌入到IDE里进行操作，这种方式是可以的：
![image](https://user-images.githubusercontent.com/6896468/55928181-6a2a4080-5c4a-11e9-9787-ee9ef751d5fb.png)

如果打包成android apk，放进手机里，然后用IDE连上手机，也可以进行poco的录制。
