### ISSUE TITLE
pycharm中无法感应出上下文帮助

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#18]
软件版本：
win10 1803：(os内部版本 17134.1)
pycharm 2017.3.4 pro

下载下来的mytestflower没有感应出poco的上下文提示。
![default](https://user-images.githubusercontent.com/38519076/39518644-4cde1ec0-4e36-11e8-88b7-3290ff069476.png)

**Comment by adolli** [comment]
hi @bs111, 抱歉，之前一直都忘记将pyi文件一起打包了，麻烦`pip install -U pocoui`即可有自动补全提示。

**Comment by bs111** [comment]
嗯 大神 
现在使用最新的版本好了

**Comment by adolli** [comment]
如果遇到该有的自动补全没有弹出来，请随时reopen这个issue。
