### ISSUE TITLE
通过下标操作控件，不同手机识别有偏差。

### ISSUE THREAD

**Issue by fendoucg2019** [AirtestProject/Poco#181]
**描述问题bug**
实例：在oppo r9上通过 poco("Layout")[7].offspring("list_view_select").child("item_select")[0].child("btn_select2").click()这个语句 能 操作玩法选择；但是在vivi x9上运行该语句时，提示：list index out of range，下标越界。在vivi x9上需要  ### #poco("Layout")[4].offspring("list_view_select").child("item_select")[0].child("btn_select2").click()才能操作玩法。将      poco("Layout")【7】改为      poco("Layout")【4】      才能在vivo x9上点击到同样的位置。

**预期效果**
无论是否换设备，同样的语句在不同的设备都能执行，不然，维护成本加大

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python3.6.7`

**poco 版本:** `1.0.76`

**设备:**
 - 型号: [vivo x9；oppo R9]
 - 系统: [vivo x9：Android :7.1.2 ；OPPO R9：Android 5.1]

**Comment by yimelia** [comment]
不同型号手机不能排除因为分辨率或者其他原因，导致显示时的节点在数组中的位置可能不同，如果要用某个数字来获取，可能不一定能取到你希望的元素。
比如，有的手机可能一屏能显示5个节点，你可以获取到第五个元素，但是另外一台手机可能只能显示4个节点，这时候强行获取第五个元素就可能导致越界。
可以尽量用其他办法来获取，例如用元素名之类的能更准确定位到节点的方式，或者自行在脚本中增加容错，先判断是否越界再进行获取。
