### ISSUE TITLE
[Poco] Unable to Integrate Unity3D into Unity project 

### ISSUE THREAD

**Issue by rabbit0057** [AirtestProject/Poco#185]
Hi Team,

I am new to unity.
trying to Integrate unity3D into my unity project but I am getting a lot of errors in the unity console.
I have followed the PocoSDK Integration Guide but it is not working for me.
Unity version = 2018.3.12f1

Could you help me in providing a detailed guide on how to Integrate unity3D into my unity project

**Comment by rabbit0057** [comment]
I deleted

**Comment by yimelia** [comment]
Hi @rabbit0057 
Please provide the error messages in the console to help us find the problem.

**Comment by rabbit0057** [comment]
I Copied the Unity3d folder to Unity ===> Assets/Core/Commands/Scripts
then removed ngui form Unity3d folder.
I see ugui and fairygui should I need to have both gui ??

Error in console 
Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(216,10): error CS0433: The type 'JsonSerializerSettings' exists in both 'Json.NET, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by TreHack** [comment]
remove the fairygui folder

**Comment by rabbit0057** [comment]
Removed fairygui folder.

But still, I see this error still in the console 
Error in console
Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(216,10): error CS0433: The type 'JsonSerializerSettings' exists in both 'Json.NET, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by TreHack** [comment]
it seems that your unity project also use Newtonsoft.Json,  try to delete the 3rdLib floder

**Comment by rabbit0057** [comment]
after deleting the 3rdLib folder

Errors in console

Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(218,3): error CS0117: 'JsonSerializerSettings' does not contain a definition for 'StringEscapeHandling'

Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(218,26): error CS0103: The name 'StringEscapeHandling' does not exist in the current context

Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(275,56): error CS1503: Argument 2: cannot convert from 'Newtonsoft.Json.JsonSerializerSettings' to 'Newtonsoft.Json.Formatting'

Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(282,44): error CS1503: Argument 2: cannot convert from 'Newtonsoft.Json.JsonSerializerSettings' to 'Newtonsoft.Json.Formatting'

Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(292,43): error CS1503: Argument 2: cannot convert from 'Newtonsoft.Json.JsonSerializerSettings' to 'Newtonsoft.Json.Formatting'

Assets/Core/Commands/Scripts/Unity3D/PocoManager.cs(312,43): error CS1503: Argument 2: cannot convert from 'Newtonsoft.Json.JsonSerializerSettings' to 'Newtonsoft.Json.Formatting'

do I need to add PocoManager.cs in different location ??

**Comment by rabbit0057** [comment]
I have fixed the above error.
Closing

**Comment by rabbit0057** [comment]
Closing thanks @TreHack
