### ISSUE TITLE
控件位置起始位置识别错误

### ISSUE THREAD

**Issue by found1025** [AirtestProject/Poco#187]
**描述问题bug**
控件位置起始位置靠近屏幕左边缘，但控件识别出来的位置却0.555， 0.8098

**相关截图**
![企业微信截图_67679402-e67f-4541-8456-cf5b9c184100](https://user-images.githubusercontent.com/38653597/56271418-0e205a00-612b-11e9-8456-7a4893caffa6.png)

**python 版本:** `python3.7`

**poco 版本:** `1.0.76`

**设备:**
 - 型号: [三星 c9]
 - 系统: [e.g. Android 8.0]

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
这个位置是控件中心点位置（图上红点），不是边角位置。

**Comment by found1025** [comment]
赞，我以为POS是左上角的相对位置。
