### ISSUE TITLE
通过类似[0, 0, 0, 0, 0, 0, 0, 0, 0, 2]识别对象

### ISSUE THREAD

**Issue by found1025** [AirtestProject/Poco#189]
我们在测试的应该会出现一个子树，该子树的每一个结点的属性都相同，有没有一种通过类似PATH FROM ROOT里值获取对象的方式？

比如说一个当前对象的path from root为 [0, 0, 0, 0, 0, 0, 0, 0, 0, 2]， 需要获取的子节点为[0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2], 通过输入类似"0, 1, 0, 2"这样值定位具体的对象。

**Comment by yuzhujiutian** [comment]
最后你们的实现方案是？

**Comment by found1025** [comment]
现在我们是写了一个封装，从指定的UI对象开始，然后通过数组结合children的方式按传递进来的LIST一层层查找，然后返回要找的对象。






--

  谢谢！
  王亮


在 2019-06-18 16:59:52，"helloc" <notifications@github.com> 写道：


最后你们的实现方案是？

**Comment by yuzhujiutian** [comment]
@found1025 

你好，想参考你的代码，我有如下需求，也需要对指定节点的处理。



![image](https://user-images.githubusercontent.com/386347/60392105-44b52080-9b2f-11e9-9478-aabe38e6ff45.png)

部分 ui 命名易重复或与其他节点完全重复时，
想通过 path from root node 值来做硬定位，该值的优点是所有节点具有唯一性，如上图所示。

请教：
1、如果UI名称不处理，可否通过 path from root node 值来定位UI并做点击、判断是否存在等操作，
该方案是否可行？这里的可行性包括通过 paht from rood node 值来判断该UI是否存在，如果存在也能做点击等类似普通UI的操作
如果不可行，有其他推荐方案么？（图像识别除外）

**Comment by found1025** [comment]
你好，


下面就是我们现在的使用方式。实际使用时还需要添加类型和异常检查。


def get_ui_obj(parent, path):
    chd = parent.child()
    if len(path) > 1:
        return get_ui_obj(chd[path[0]], path[1:])
    else:
        return chd[path[0]]
        
filter_panel = poco("com.abc.abc:id/activity_editor_child_editmenu_top_filter")


f_letter = get_ui_obj(filter_panel, [2, 2, 1, 1])




--

  谢谢！


在 2019-06-30 12:06:31，"helloc" <notifications@github.com> 写道：


@found1025

你好，想参考你的代码，我有如下需求，也需要对指定节点的处理。

部分 ui 命名易重复或与其他节点完全重复时，
想通过 path from root node 值来做硬定位，该值的优点是所有节点具有唯一性，如上图所示。

请教：
1、如果UI名称不处理，可否通过 path from root node 值来定位UI并做点击、判断是否存在等操作，
该方案是否可行？这里的可行性包括通过 paht from rood node 值来判断该UI是否存在，如果存在也能做点击等类似普通UI的操作
如果不可行，有其他推荐方案么？（图像识别除外）

**Comment by adolli** [comment]
通过这个顺序是不准的，可能随时变化。而且这个值是内部用来做渲染排序的，不建议用来做选择

**Comment by found1025** [comment]
确实是有不准的问题。








--

  谢谢！
  王亮


在 2019-07-07 17:35:07，"adolli" <notifications@github.com> 写道：


通过这个顺序是不准的，可能随时变化。而且这个值是内部用来做渲染排序的，不建议用来做选择
