### ISSUE TITLE
Poco可以遍历一个列表所有的子item吗

### ISSUE THREAD

**Issue by liiijz** [AirtestProject/Poco#192]
比如当前界面是一个列表，我想取出所有的list item，但是poco好像只能取出当前显示的那部分，一般怎么能遍历所有的，用的是 poco('list_name').children() 是不是需要自己增加滑动操作

**Comment by yimelia** [comment]
是的，Poco的操作是模拟人在使用时的操作，看不到的元素就不一定能够获取到了（也点不到），可以自己加滑动操作把整个屏幕都划一遍来获取，但是还要自己判断下元素有没有重复获取。
