### ISSUE TITLE
在哪里修改poco操作中心点

### ISSUE THREAD

**Issue by kongguliu** [AirtestProject/Poco#196]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
在点击某个UI树的节点，比如按钮的时候，在执行脚本时，会先找到按钮的区域，然后再对区域的中心点进行点击，是这样的吧。
**复现步骤**

**预期效果**
想不对中心点进行操作，比如说操作点想在中心点的下面一点点

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
可以在取到poco的位置信息后，根据当前的分辨率计算出实际点击坐标后，自己加一点点偏移，然后touch

**Comment by kongguliu** [comment]
> 可以在取到poco的位置信息后，根据当前的分辨率计算出实际点击坐标后，自己加一点点偏移，然后touch

那在哪个.py里面添加代码呢，可以添加代码的位置是哪里

**Comment by yimelia** [comment]
可以写在你自己的py代码里，然后自己调用它

**Comment by kongguliu** [comment]
> 可以写在你自己的py代码里，然后自己调用它

emmmm。可以告诉我它计算中心点的位置的代码在哪里吗，我研究一下，看一下怎么改

**Comment by yimelia** [comment]
首先，可以自行查找poco的源码，来找到你想修改的位置。请在本地python环境中`pip install pocoui`，然后自行修改本地python环境中的poco代码，改好后如果希望在IDE生效，请在IDE的设置里找到Custom Python那一栏，添加自己的python.exe环境所在路径。

其次，如果是因为整体坐标都有偏移，希望每一个点都偏移一定位置，可能是因为窗口的标题栏影响到了窗口位置大小判断，可以参考这个[issue](https://github.com/AirtestProject/Poco/issues/177)

最后，如果只是某几个按钮或控件希望加一点偏移量，可以自己在自己的脚本里实现一个函数，对于查找出来的控件坐标进行自定义调整。
