### ISSUE TITLE
我已经安装了pocounit，但是执行import pocounit时报错：No module named 'pocounit'，请问是什么情况？

### ISSUE THREAD

**Issue by appp-deng** [AirtestProject/Poco#197]
**你遇到了什么我们这个库解决不了的问题？**
我已经安装了pocounit("pip install pocounit")，但是执行import pocounit时报错：No module named 'pocounit'，请问是什么情况？

**Comment by yimelia** [comment]
在自己的python环境中执行的，还是在AirtestIDE里？
如果是在IDE里，需要参考这个[文档](http://airtest.netease.com/docs/cn/7_settings/1_ide_settings.html#python)。
如果是自己的python环境中执行，需要自行检查环境是否一致，是否成功安装等其他问题。
