### ISSUE TITLE
使用本地Python，在命令窗口运行脚本出错

### ISSUE THREAD

**Issue by kongguliu** [AirtestProject/Poco#199]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
这adb我到路径下看了，确实存在的
![image](https://user-images.githubusercontent.com/18191658/57234965-6b396c80-7054-11e9-8756-dcf31c431f1f.png)
![image](https://user-images.githubusercontent.com/18191658/57235033-90c67600-7054-11e9-996c-ab6b0618e6ac.png)

```

**复现步骤**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
看起来是因为希望测试windows下的unity窗口，但是没有先指定连上那个窗口导致的。可以参考[文档](http://airtest.netease.com/docs/cn/2_device_connection/5_windows_connection.html#id4)，在运行时的命令行后面加上对应的 `--device windows:///窗口句柄`
