### ISSUE TITLE
Linux的docker容器里面运行airtest提示error: could not install *smartsocket* listener: Address already in use,执行失败

### ISSUE THREAD

**Issue by jeniva** [AirtestProject/Poco#200]
**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
1、在Linux里面通过Python 脚本.py 或者airtest 脚本.air方式都会出现截图所示的错误，导致用例执行失败，然后所有手机都不在线了，重启docker才恢复。我需要做什么处理，才能在Linux里面执行成功。
2、Android4.2的手机是不是装不了pocoserver.apk，提示安装失败
```
（在这里粘贴traceback或其他报错信息）
```
[pocoservice.apk] stdout: 
com.netease.open.pocoservice.InstrumentedTestAsLauncher:
[pocoservice.apk] stderr: 
[12:41:00][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/dist-packages/airtest/core/android/static/adb/linux/adb -s 882QADT8EJEA5 shell am force-stop com.netease.open.pocoservice
error: could not install *smartsocket* listener: Address already in use
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon
[2019-05-09: 12:41:02] no devices, please check the connection ! 
[12:41:03][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/dist-packages/airtest/core/android/static/adb/linux/adb -s 882QADT8EJEA5 shell am start -n com.netease.open.pocoservice/.TestActivity
[12:41:03][DEBUG]<airtest.core.android.adb> /usr/local/lib/python2.7/dis

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)
在Linux里面需要怎么配置adb，还是其他的，才能让他正常执行，已经chmod+x有权限了。

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![image](https://user-images.githubusercontent.com/8514029/57454285-0a4fa580-729b-11e9-9886-952f4a06c9bb.png)
![image](https://user-images.githubusercontent.com/8514029/57454514-9feb3500-729b-11e9-8e17-d19f6a78407a.png)

**python 版本:** `python2.7` 、pyhon3.5都试了。

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到
airtest==1.0.26
pocoui==1.0.76

**设备:**
 - 型号: 魅族
 - 系统: [e.g. Android 8.1]
 - (别的信息)
Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-34-generic x86_64)

**其他相关环境信息**
在linux ubuntu16.04上运行异常，在windows上正常

**Comment by jeniva** [comment]
![image](https://user-images.githubusercontent.com/8514029/57455257-57347b80-729d-11e9-927c-616c694d80a8.png)

**Comment by yimelia** [comment]
看一下端口占用的情况，5037端口是否可用？

**Comment by jeniva** [comment]
这个问题我解决了，是adb版本冲突导致的，把airtest里面的adb复制到Python的adb里面就好了
