### ISSUE TITLE
请问poco如何双击？

### ISSUE THREAD

**Issue by saint228** [AirtestProject/Poco#203]
使用poco时，发现形如 poco("控件").double_click()的方法会报“NotImplementedError”的异常。

检查代码发现，\Python3.7\Lib\site-packages\poco\pocofw.py 下的第259行：

```
 def double_click(self, pos):
        raise NotImplementedError
```

并没有写double_click的逻辑代码？

我试图换着用airtest库里的double_click()方法：
```@logwrap
def double_click(v):
    if isinstance(v, Template):
        pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
    else:
        try_log_screen()
        pos = v
    G.DEVICE.double_click(pos)
    delay_after_operation()
    return pos
```

这个方法是可以实现双击，但间隔很慢，两次点击之间几乎要花费2秒时间。达不到双击的效果。

请问下，效果最好的双击究竟是怎么样的方法？

**Comment by yimelia** [comment]
poco 是有实现双击接口的，更新到最新版本看看

**Comment by saint228** [comment]
> poco 是有实现双击接口的，更新到最新版本看看

我的pocoui是1.0.76。刚刚试着pip再看一下，已经是最新版本了。
能否告知双击功能实现的具体方法路径，能给个实例就更好了。谢谢。

**Comment by yimelia** [comment]
对应使用的Poco是什么平台的？unity, cocos, 安卓原生？

**Comment by saint228** [comment]
unity

> 对应使用的Poco是什么平台的？unity, cocos, 安卓原生？

[https://imgchr.com/i/EzhmHx](url)

**Comment by yimelia** [comment]
或者用airtest的 double click接口吧，是在手机上点击吗？

**Comment by saint228** [comment]
> 或者用airtest的 double click接口吧，是在手机上点击吗？

我用的模拟器。

airtest的double_click 太慢了。

[02:15:55][DEBUG]<airtest.core.android.adb> D:\Python3.7\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:62025 shell input tap 0 1
[02:15:57][DEBUG]<airtest.core.android.adb> D:\Python3.7\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:62025 shell input tap 0 1
custom tearDown

一次双击操作耗时2秒。

**Comment by yimelia** [comment]
不要勾选`use adb touch`，再连模拟器后重试看看，adb touch 是比较慢的

**Comment by saint228** [comment]
> 不要勾选`use adb touch`，再连模拟器后重试看看，adb touch 是比较慢的

感谢，不使用adb touch以后果然快很多。airtest的double_click()已经令人满意。

不过poco的double_click()究竟该怎么用呢？

**Comment by yimelia** [comment]
可能是poco安卓方面的double click没实现，我们后续完善一下

**Comment by saint228** [comment]
非常感谢。
