### ISSUE TITLE
如何获取 unity 上控件的某些属性

### ISSUE THREAD

**Issue by lornetian** [AirtestProject/Poco#204]
**你遇到了什么我们这个库解决不了的问题？**
Payload details:
	  type :  Raw.Image 
	  name :  LineImage 
	  visible :  True 
	  pos :  [0.376576543, 0.3348856] 
	  size :  [0.42396757, 0.589679956] 
	  scale :  [1.0, 1.0] 
	  anchorPoint :  [0.5, 0.5] 
	  zOrders :  {'global': 0.0, 'local': -100.0} 
	  clickable :  False 
	  components :  ['RectTransform', 'CanvasRenderer', 'RawImage', 'Shadow'] 
	  texture :  b'3b0301bf-e061-44fd-b0c2-ddacf.png' 
	  _ilayer :  5 
	  layer :  b'UI' 
	  _instanceId :  -8998 
从 IDE 的 UI 树中选取一个控件，可以在log 查看窗中看到许多属性，但是在脚本中无法获取这些属性。如 texture 的字符串怎么获取呢，poco.unity 貌似没看到有 getattr 方法

**描述一下你想如何解决这个问题**

**额外信息**
(运行环境、设备、相关参考信息，如果有的话。)

**Comment by yimelia** [comment]
可以用`.attr`来获取，参见[文档](https://poco.readthedocs.io/zh_CN/latest/source/README.html#get-object-properties)

**Comment by lornetian** [comment]
> 可以用`.attr`来获取，参见[文档](https://poco.readthedocs.io/zh_CN/latest/source/README.html#get-object-properties)

![image](https://user-images.githubusercontent.com/49709406/58623394-7bb1cf80-8300-11e9-9aa6-7b221c22ce67.png)
没找到有 attr，setattr倒是有

**Comment by lornetian** [comment]
谢谢，刚开始用，源码还没来得及祥看，主要靠代码提示看的可用方法
