### ISSUE TITLE
cocos-lua的poco识别控件位置有问题

### ISSUE THREAD

**Issue by luckyuki** [AirtestProject/Poco#21]
问题1：
![image](https://user-images.githubusercontent.com/26541375/40156780-2c35af78-59ce-11e8-8681-04928086d4c5.png)
运行时提示点击坐标超出屏幕。
问题2：
另外一个机器华为mate8，识别出的控件位置与屏幕上的真实位置相差1/3屏幕

**Comment by adolli** [comment]
你确认一下这个按钮的位置是否真的超出屏幕，能看下在屏幕中检视出来的位置截图吗？

**Comment by luckyuki** [comment]
![image](https://user-images.githubusercontent.com/26541375/40216456-59af8ed0-5a99-11e8-8f69-1d710922542a.png)

**Comment by adolli** [comment]
因为这个你点击的UI已经在屏幕很边缘的位置了，他的anchor point已经在屏幕外，你适当偏移一下吧。
```python
poco(xxx).focus([0.5, 0.5]).click()
```
