### ISSUE TITLE
大佬们，请问可以在AirtestIDE里面调用unittest吗？可以的话要怎么调用？

### ISSUE THREAD

**Issue by appp-deng** [AirtestProject/Poco#212]
大佬们，请问可以在AirtestIDE里面调用unittest吗？可以的话要怎么调用？之前找了一下帮助文档但是没有找到详细说明

**Comment by yimelia** [comment]
AirtestIDE里暂时不行，如果要用unittest的话，建议用pycharm或者sublime之类的其他python IDE

**Comment by appp-deng** [comment]
那在IDE里可以进行单元测试吗？
