### ISSUE TITLE
手机竖屏模式下，应用打开后，自动旋转为横屏。这个时候，控件点击的位置就不对了，会偏移。

### ISSUE THREAD

**Issue by loneyao** [AirtestProject/Poco#216]
描述问题bug
手机竖屏模式下，应用打开后，自动旋转为横屏。这个时候，控件点击的位置就不对了，会偏移。

**Comment by yimelia** [comment]
请根据issue模板来描述问题，提供更多信息和截图：
手机型号、poco是什么类型、问题代码、如果有相关log也请一并提供、点击的偏移是什么样的偏移，固定像素偏移还是横竖屏都判断错误的便宜

**Comment by loneyao** [comment]
已解决

**Comment by loneyao** [comment]
OPPO A83
ColorOS V5.2.1
android 7.1.1
我是应用启动之后先进行了pocoAndroid = AndroidUiautomationPoco(use_airtest_input=True初始化, screenshot_each_action=False)去对应用打开权限的点击，点击完毕后，我再等待35秒后去poco = UnityPoco()初始化，这个时候，poco控件点击的位置就偏了。就类似我下面图一样，大的是正常的一个大大的按钮，会点到旁边小的位置去。
![QQ20190619-094854](https://user-images.githubusercontent.com/12229795/59810232-d99d6a00-9336-11e9-9ccb-c4eda549303f.png)
