### ISSUE TITLE
【mark】poco的字符输入set_text函数在部分机型上不工作时可以用airtest的text函数替代

### ISSUE THREAD

**Issue by yuzhujiutian** [AirtestProject/Poco#217]
poco的字符输入set_text函数在部分机型上不工作时可以用airtest的text函数替代

from airtest.core.api import text as airtest_text

poco('xxx').set_text('yyy')   # 如小米6手机本行代码执行正常
if not poco('xxx').get_text():    # set_text 不报错但输入框中无字符 yyy
    airtest_text('yyy')    # 使用 airtest 的 字符输出函数 text

其中 if 代码块用途
兼容类似华为畅玩4X android 4.4.4 等早期设备无法通过 poco('xxx').set_text('yyy') 实现输入的处理。

**Comment by yimelia** [comment]
备忘：对应的文档链接在[这里](http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html#airtesttext)
