### ISSUE TITLE
unity引擎中如何较准确的选中某个GameObject

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Poco#223]
公司使用unity开发的游戏中有大量建筑模型，人物模型等，通常是需要点击某个具体的NPC或建筑才能弹出UI，有没有办法可以精确定位NPC对象或者建筑对象（像捕获某个具体的UI控件一样）

**Comment by yimelia** [comment]
自行根据NPC对象或建筑对象的属性进行定位。
