### ISSUE TITLE
请问poco可以对text里的内容模糊匹配吗？

### ISSUE THREAD

**Issue by appp-deng** [AirtestProject/Poco#225]
我想定位评论区的头部
它的name是android.view.View，没有识别性
text是“评论（9）”，但是括号的数字会变，请问可以对text的内容进行模糊匹配吗？

**Comment by yimelia** [comment]
可以使用正则，这是个例子：
```
poco(textMatches='^据点.*$', type='Button', enable=True)
```
更多示例请查阅Poco文档https://poco.readthedocs.io/zh_CN/latest/source/README.html#working-with-poco-objects

**Comment by shijianzhihu** [comment]
> 可以使用正则，这是个例子：
> 
> ```
> poco(textMatches='^据点.*$', type='Button', enable=True)
> ```
> 
> 更多示例请查阅Poco文档https://poco.readthedocs.io/zh_CN/latest/source/README.html#working-with-poco-objects

你好，我现在使用的是AirtestIDE v1.2.1 , 我使用poco正则无法匹配到UI，我的代码是：
money_text= poco(textMatches=".*应付金额.*").get_text()
![](https://user-images.githubusercontent.com/26112446/62118875-1030b200-b2f1-11e9-84b5-df16932cdecd.png)
运行报错：poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "text matches .*应付金额.*

我这样写是可以正确匹配到的：
money_text = poco(text="应付金额：0.01元").get_text() 

望解惑 thanks
