### ISSUE TITLE
在pycharm里运行脚本提示raise RpcTimeoutError(self)

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Poco#226]
同样一份脚本在airtestIDE里正常运行，在pycharm里运行报RpcTimeoutError(self)异常
附报错截图：
![2](https://user-images.githubusercontent.com/26775694/60811810-9e1def00-a1c2-11e9-98db-ec78ea4f1680.jpg)

附脚本：

[test1.txt](https://github.com/AirtestProject/Poco/files/3368427/test1.txt)

**Comment by yimelia** [comment]
初始化一次poco对象即可，没必要在每个子函数里都初始化一次
