### ISSUE TITLE
小米5S运行带参数的脚本报错

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Poco#229]
小米5s在命令行输入如下命令，运行时报错
py -3.6 test2.py android:///10.0.2.44:7555?ori_method=ADBORI&&touch_method=ADBTOUCH
即设备信息通过系统参数传入
报错截图如下：
![3](https://user-images.githubusercontent.com/26775694/61204285-61e91200-a71f-11e9-86ff-36b87541edc0.jpg)

如果将设备信息在脚本写死，不通过系统参数传入，即直接运行py -3.6 test2.py，则顺利执行无报错

vivox23使用两种方式执行都正常不会报错（传参的方式会在脚本结束时提示“'touch_method' 不是内部或外部命令，也不是可运行的程序或批处理文件。”，不知道如何去掉）

附脚本：
[test2.txt](https://github.com/AirtestProject/Poco/files/3391471/test2.txt)

**Comment by ymdhtt** [comment]
@yimelia 已找到解决方法，传参时用“”引起来就不会报错，即
py -3.6 test2.py “android:///10.0.2.44:7555?ori_method=ADBORI&&touch_method=ADBTOUCH”
但是具体原因未知，希望你们有空时可以指点迷津

**Comment by yimelia** [comment]
参考[这个](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id10)

命令行中如果有出现 ^ < > | & 这些字符，可能都需要转义才能生效，因此如果连接字符串中需要写 && 时，在windows下需要改写成 ^&^& ，添加一个 ^ 符号进行转义
