### ISSUE TITLE
如何将命令行模式运行时的日志全部保存

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Poco#230]
@yimelia 
通过命令行模式运行会有大量日志，但是最后保存下来的只有操作信息和断言信息
如何将所有日志内容全部保存下来呢？
有时游戏或设备初始化的时候就报错了（还没运行测试用例），只能在命令行里看到Log，没有作为文本信息保存起来，后期查找不方便

**Comment by yimelia** [comment]
airtest里的log使用了python的`logger`模块，可以自行查阅logger的用法
