### ISSUE TITLE
poco 识别unity 2018 android ui  失败

### ISSUE THREAD

**Issue by alexhjb001** [AirtestProject/Poco#241]
##(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
aritest 识别unity 2018 android ui game 失败 

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![1](https://user-images.githubusercontent.com/53072613/61513768-b3034980-aa30-11e9-8b72-40ed6e9cd23b.png)

**python 版本:** `python3.7`

**poco 版本:** `1.0.76`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [nexus p6]
 - 系统: [Android 8.0]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
1. 请问是否已经接入了poco-sdk？
2. 请提供在获取UI失败时，命令行窗口里的报错内容

**Comment by yimelia** [comment]
请先查看文档，接入POCO-SDK后再使用。
http://airtest.netease.com/docs/cn/6_poco_framework/poco_quick_start.html#id2
