### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。'

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/Poco#243]
循环svgbox中的所有元素报错
svgbox中大概有几百个元素，名字中带序号的
每次迭代的时候就会报错，前几个不会报错
![QQ截图20190719215207](https://user-images.githubusercontent.com/52645118/61574849-a7c72100-aaf7-11e9-9d63-7c59bce35781.png)

**Comment by yimelia** [comment]
为了方便定位此问题，请依次回答以下问题：

1. 本问题与https://github.com/AirtestProject/AirtestIDE/issues/479 是否重复？

2. poco类型是什么？

3. 直接在IDE中连上对应的设备，选择正确的poco类型后，能否看到UI结构树？

4. 如果能正确看到UI结构树，根据你的描述，是在运行到某些特定脚本代码时才会报这个错吗？如果是，请贴出代码。

**Comment by abcdd12** [comment]
1.是重复了，那个提错地方了
2.类型是安卓
3.可以看到结构树，下边我贴个图
4.帮忙看下我的代码，运行第一次的时候没事，第二次的时候就开始报这个错了
![QQ截图20190722101311](https://user-images.githubusercontent.com/52645118/61601729-563ea380-ac69-11e9-8937-dd038d2bfdd4.png)

**Comment by yimelia** [comment]
你的代码里只初始化了`svgbox = poco("svgbox")`，没看到有后续的操作，如果仅仅只运行这一行代码也会报错吗？

**Comment by abcdd12** [comment]
运行第一次的时候不会报错，第二次开始就会报错了

![QQ截图20190722102524](https://user-images.githubusercontent.com/52645118/61602135-082a9f80-ac6b-11e9-8b3c-f021f3d6eb13.png)

**Comment by abcdd12** [comment]
如果只运行svgbox = poco("svgbox")  没问题
加上下边的print就会报错了

**Comment by yimelia** [comment]
修改一下源码，不要去取这个svgbox的内容了，而是换一个简单一点的节点进行获取+操作（注意，如果只是写xx=poco("xxx")这样的代码， 实际上是不会执行的，要写上具体的操作比如.click()才会真正去执行）
试一下分开做以下两件事情看看结果分别是什么：
1. 去获取一个简单的节点并且.click()它，最好不要像svgbox那样有很多子节点的，而是自己就是一个普通节点。双击UI树上的节点可以自动生成代码。

2. 双击svgbox列表中的第0个元素生成代码，然后对它进行操作，比如poco("colortag0").click()

看看分开运行这两种代码有没有都报错

**Comment by abcdd12** [comment]
工作需求是要把svg中的节点都要点一次，然后再进行判断，现在准备先实现都点击一遍，如果一个一个的点会很慢，想用代码实现
你说的我试了试确实不会报错

**Comment by abcdd12** [comment]
想按照svgbox结构下的显示顺序点击节点

**Comment by yimelia** [comment]
那就可能是获取节点的方式有问题，也就是说，`poco("svgbox")[0]`可能是不行的
具体如何获取子节点，可以参考poco的[api文档](https://poco.readthedocs.io/zh_CN/latest/source/README.html#iterate-over-a-collection-of-objects)。我这里因为没有装你实际的app，并不能直接帮忙写代码，请自行根据文档尝试编写。

**Comment by abcdd12** [comment]
哦 好的 谢谢了，虽然代码没完成，但是报错的原因还是找到了  非常感谢

**Comment by summerAli** [comment]
@abcdd12   您好，请问这个问题，后来是怎么解决的呢？
我这边也遇到类似的问题了：
脚本里面：先迭代遍历一组UI后，进行click(）点击操作；如果只跑一次，是正常的；如果进行循环测试，测试可以正常进行，但测试结束后会报错 。
