### ISSUE TITLE
Airtest是否支持对接stf进行自动化测试？

### ISSUE THREAD

**Issue by AnnaJingBaby** [AirtestProject/Poco#244]
Airtest是否支持对接stf进行自动化测试？

**Comment by yimelia** [comment]
两者之间并没有冲突

**Comment by AnnaJingBaby** [comment]
有相关的demo么？

**Comment by yimelia** [comment]
没有。
Airtest支持远程连接设备，这个设备不需要非得在本地，因此同样支持远程STF部署出来的设备。
不知道你需要什么内容的demo。

**Comment by AnnaJingBaby** [comment]
远程STF部署出来的设备也是直接根据设备的ip来操作么，不需要获取STF的相关权限吗？

**Comment by yimelia** [comment]
远程部署出来可以用adb connect xxx去连，在IDE里有个连接远程设备，可以填入这段东西`adb connect IPxxx`来连
