### ISSUE TITLE
poco-android截取app长图

### ISSUE THREAD

**Issue by neoguo85** [AirtestProject/Poco#245]
**你遇到了什么我们这个库解决不了的问题？**
直接调用方法截取长图，比如有些app一个界面显示不完，需要多图拼接。

**描述一下你想如何解决这个问题**
如果可能，希望poco-android支持直接截取长图，用一个新的方法或者在现有截图方法里加一个类似参数。

**额外信息**
(运行环境、设备、相关参考信息，如果有的话。)

**Comment by yimelia** [comment]
可以自行用Pillow模块的功能进行图片拼接
