### ISSUE TITLE
XP机器启动AirtestIDE.EXE 提示无法定位程序输入点 GetFinalPathNameByHandleW于动态链接库 KERNEL32.dll

### ISSUE THREAD

**Issue by chen072086** [AirtestProject/Poco#248]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
windows - XP  sp3的系统
从官网下载的IDE最新版本2019-04-16 win32版本的安装包
解压后，启动AirtestIDE
XP机器启动AirtestIDE.EXE 提示无法定位程序输入点 GetFinalPathNameByHandleW于动态链接库 KERNEL32.dll

（在这里粘贴traceback或其他报错信息）
```

**复现步骤**
1.从官网下载的IDE最新版本2019-04-16 win32版本的安装包
2.解压后，启动AirtestIDE


**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![image](https://user-images.githubusercontent.com/20700258/61884353-ab5f0b80-af2e-11e9-9fe7-3e5c18dceac2.png)


**python 版本:** `python2.7`

XP机器启动AirtestIDE.EXE 提示无法定位程序输入点 GetFinalPathNameByHandleW于动态链接库 KERNEL32.dll

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
非常抱歉，XP系统过于老旧，我们没有做过兼容，由于人手不足以及市场占有率也很低，因此暂时不会对此进行兼容
