### ISSUE TITLE
测试评论时，跑到输入评论内容步骤时直接给我发送了，这是什么机制我还没打算发送呢

### ISSUE THREAD

**Issue by appp-deng** [AirtestProject/Poco#249]
iOS测试评论功能，手动在模拟器上发评论需要先写好评论内容，点击键盘的“send”键才会发送（未登录状态点击“send”会提示登录）
-------------------------------
# -*- encoding=utf8 -*-
__author__ = "gaokaozhitongche"
from airtest.core.api import *
auto_setup(__file__)
from poco.drivers.ios import iosPoco
poco = iosPoco()
#点击评论输入框定位
poco("TextView").click()
#评论内容
text("测试”)
----------------------------------
跑脚本时如果是已登录，运行到text(“测试”)时直接就给我发送了，如果未登录直接提示我登录，嗯。。。。这是什么机制啊我还没打算发送呢

**Comment by yimelia** [comment]
请查阅API文档：
https://airtest.readthedocs.io/zh_CN/latest/all_module/airtest.core.api.html#airtest.core.api.text
