### ISSUE TITLE
我在AirtestIDE软件上可以运行，命令行无法运行 

### ISSUE THREAD

**Issue by tong-yao** [AirtestProject/Poco#250]
**分类：bug**

**详细描述问题bug：**
我在AirtestIDE都已经写好，运行也ok，但是命令行就不可以了（点击可以，滑动不可以）
🌟
**复现步骤：**
下面👇是我的代码，几乎没写什么，但是无法滑动这一下，我注释的那行，点击就可以
`# -*- encoding=utf8 -*-
__author__ = "a1"

from airtest.core.api import *

from poco.drivers.ios import iosPoco

poco = iosPoco()
poco("ScrollView").swipe([-0.4666, 0.0057]) 这个滑动无法动
poco("设置").click()   这个点击事件可以

auto_setup(__file__)`

这是我的代码，几乎什么也没写啊，
在命令行里写的这个，没保存日志，就是官网给的命令👇我改了个路径
python3 -m airtest run aso/one3.air --device ios:///http://127.0.0.1:8100
🌟

**python 版本:** `python3.x`
python 3.6.0
🌟

**操作系统:** `Windows7 64bit`
mac 10.14.5 (18F132)
🌟

**手机设备信息:**
iphone6s
🌟

 - 手机型号:
 - Android系统版本号: [e.g. Android 8.1]
ios 11.2.1（15C153）
🌟
 - (别的信息)

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：
v.1.2.1
🌟
**截屏**
强烈建议带上截图，包括IDE本身的截图和后面的黑窗口的报错信息的截图（尽量完整）。

![](https://user-images.githubusercontent.com/43436575/61924914-7be6e800-af9c-11e9-9150-19fabfd6c799.png)

**Comment by EraChen233** [comment]
xcode版本是什么？proxy命令行和xcode的log窗口有异常输出吗？

**Comment by tong-yao** [comment]
xcode 10.1 (10B61)（当时选择这个版本好像是因为oc的代码不支持更高的吧）
xcode的log窗口没有异常输出，
![image](https://user-images.githubusercontent.com/43436575/61931303-d12df400-afb2-11e9-8290-54d4aca3d1f1.png)一直都是这些
proxy命令行也没有异常输出，都是这个
![image](https://user-images.githubusercontent.com/43436575/61931355-f6bafd80-afb2-11e9-8d49-b6e385411c62.png)

**Comment by EraChen233** [comment]
你上面的信息都是实时获取iOS手机截屏的log，把IDE关了，只开命令行运行代码，然后查看swipe动作发生报错的时候，他们的输出分别是什么

另外现在iOS－tagent已经更新支持xcode 到版本 10.2.1

**Comment by tong-yao** [comment]
ok，我一会去更新一下xcode以及iOS－tagent

我把IDE关闭了，proxy的log，一直在循环这些，循环19次，显示资源不可用，我不清楚是什么资源不可用
![image](https://user-images.githubusercontent.com/43436575/61933052-7c40ac80-afb7-11e9-8614-c5c2de59208e.png)

xocde这边，循环到7再循环一次，共循环5次 ，579.14s  583.36s，共用时4秒左右
![image](https://user-images.githubusercontent.com/43436575/61933240-fe30d580-afb7-11e9-98e7-7b6d5130f292.png)
![image](https://user-images.githubusercontent.com/43436575/61933271-14d72c80-afb8-11e9-9985-999a6ada7f3f.png)

**Comment by EraChen233** [comment]
红框标出的log不用管的
你重新截的图片，也都是获取截屏和UI结构的。可以确认一下，实时控制手机的网页、IDE都关了吗？你发的截图还是没有有效的错误信息哦

![image](https://user-images.githubusercontent.com/5961185/61933877-82378d00-afb9-11e9-87c9-bc47b3414db1.png)

**Comment by tong-yao** [comment]
真的关了啊，如果这样还不行，那就卸载才是关了啊😂
我没有任何控制手机的网页，这个虽然也是获取截屏和UI结构的，但是和有点之前不一样了，这次是我执行命令才获取的，Xcode和iproxy都是，只有执行命令才获取
![image](https://user-images.githubusercontent.com/43436575/61934253-7b5d4a00-afba-11e9-8015-3a850ab74a4d.png)
![image](https://user-images.githubusercontent.com/43436575/61934313-97f98200-afba-11e9-952f-f5e6231a9e3a.png)
不管怎样，先在这里十分感谢您的帮助。希望能解决这个bug，

**Comment by tong-yao** [comment]
你可以通过这个给我任何帮助吗？因为我只有滑动不可操作（我只实验了滑动和点击😂），所以我认为不是我环境的事，或者什么xcode或iproxy的问题。可能我代码错误或........
![image](https://user-images.githubusercontent.com/43436575/61939205-51f5eb80-afc5-11e9-913b-01b5c61dcc40.png)

**Comment by EraChen233** [comment]
并不是说你的环境的问题哦
既然你能在IDE上跑，就说明你代码是可以运行的
但是我在我自己的电脑上试过滑动，不管是IDE还是命令行的方式，真机还是模拟器，都可以成功运行的。
我这边没办法复现你的问题，所以我需要你提供更多的信息给我，帮助我定位问题发生在哪里。

**Comment by EraChen233** [comment]
你看一下你的facebook-wda 版本是多少
我这边的版本是facebook-wda(0.2.1)，可以成功运行

![image](https://user-images.githubusercontent.com/5961185/61940878-e7df4580-afc8-11e9-8a84-3587f83217fc.png)

**Comment by tong-yao** [comment]
😅我的这个是 0.3.4
![image](https://user-images.githubusercontent.com/43436575/61942045-3097fe00-afcb-11e9-8ea6-0e6e8a1367de.png)

十分感激，have a good day

**Comment by EraChen233** [comment]
换一下 facebook-wda 的版本，重新跑一下试试

**Comment by tong-yao** [comment]
嗯嗯，已经成功了，谢谢您

**Comment by jeniva** [comment]
我有遇到了这个问题，滑动不了，这个facebook-wda(0.2.1)版本去哪里下载呢？
