### ISSUE TITLE
为了提高效率, 能不能添加一种在当前dump file中查询的模式而不是再次的发送request 到 apk的server, 或者能不能一次性获取多个UIObjectproxy？

### ISSUE THREAD

**Issue by woshichuanqilz** [AirtestProject/Poco#261]
**你遇到了什么我们这个库解决不了的问题？**
需求是这样的，我需要便利一个评论列表, 每一条评论项里面包括, 内容时间作者和是否点赞, 一共4项内容。我查看了一下时间，消耗每一次请求，大概需要0.3秒到0.4秒我觉得这个时间实在是有点太长了。
![image](https://user-images.githubusercontent.com/11295355/62521176-ba648880-b861-11e9-97d3-840218fb6d01.png)

**描述一下你想如何解决这个问题**
所以我现在有两个想法
1. 因为在遍历评论的时候, 我的我的软件界面不是一直在动的只有在这一页面刷完之后，我才会下拉到下一个界面。所以在我见面没有变的时候，我没有必要每次都去请求apk服务端。我可以dump出来总的文件, 在界面没有变化的时候，一直在这个dump文件里面搜索就OK了。所以这个步骤可以做成静态的。

2. 另一个想法就是，我能不能一次请求多个搜索, 因为在我这种情况，我的4次请求是相对并列的一种情况如果能把这4次请求合并的话，我只要走一次，HTTP发送就OK了

**额外信息**
无

**另**
1. 能不能说下你们APK端的搜索的算法或者告诉我实现代码在哪我自己看, 不是很熟悉安卓的代码。 谢谢了。
2. IDE的源码你们是没有提供吗? 我看airtestproject 主页上 ide 没有代码

**Comment by yimelia** [comment]
你描述的问题不是特别清楚，但是我猜测poco提供的一个UI冻结功能，也许能够满足你的需求：
https://poco-chinese.readthedocs.io/zh_CN/latest/source/doc/poco-example/optimize_speed_by_freezing_UI.html

AirtestIDE目前是没有开源的
