### ISSUE TITLE
引擎层支持点击、滑动等操作，不依赖于adb进行事件触发

### ISSUE THREAD

**Issue by kicasstt** [AirtestProject/Poco#268]
**引擎层支持点击、滑动等操作，不依赖于adb进行事件触发**
大神，这个特性能否实现，比如说在unity3d上实现~

**Comment by yimelia** [comment]
暂时没有
我们希望是尽量能够模拟用户的操作，如果直接操作引擎层的话，有可能有些问题不能被发现
