### ISSUE TITLE
建议poco加入父节点的方法判定

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#27]
poco没有父节点的方法判定，我想排除这个最近使用中列出来的语言列表。
其实，我只要有方法通过判定我获得到的所有叶子节点中
     其中的每个的叶子节点的，第三级别的父节点是不是“ name :  com.xxx.xxx:id/recent_listview”就好了
但是poco没有这个方法.

![image](https://user-images.githubusercontent.com/38519076/40873140-79ce210e-668d-11e8-9f81-26e4de061d93.png)

![tim 20180602180258](https://user-images.githubusercontent.com/38519076/40873231-33f2ecd0-668f-11e8-8093-f7b32d96507b.png)

**Comment by adolli** [comment]
那你可以直接这样比较
```python
targets = [...]
for n in poco('name : com.xxx.xxx:id/recent_listview').children():
   if n.attr('resourceId') in targets:
        ...
```

**Comment by bs111** [comment]
对着样做也行

**Comment by adolli** [comment]
以后可能会考虑加上去

**Comment by jekiki** [comment]
poco中只能寻找兄弟元素，子元素和后代元素，但是无法寻找其父元素，祖先元素。

拿到父元素就可以直接遍历其兄弟元素，怎么直接获取其兄弟元素的列表

**Comment by yimelia** [comment]
已经添加了`.parent`接口

**Comment by jekiki** [comment]
> 已经添加了`.parent`接口
poco(text="我的").parent or poco(text="我的").parent()

ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "D:\workspace\airtest\xyqg.air\xyqg.py", line 184, in <module>
    poco(text="我的").parent
AttributeError: 'UIObjectProxy' object has no attribute 'parent'
请问如何从UIObjectProxy调用或转换为可以调用parent的类

**Comment by yimelia** [comment]
当前最新版本的IDE尚未更新，如果使用了本地poco可以更新到最新版本就可以直接 `.parent()`。
如果只使用IDE的话可以稍等下，本周我们很快会放出一个新版本的IDE的。

**Comment by jekiki** [comment]
thank you!

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=pchengzhwang&uid=pchengzhwang%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22pchengzhwang%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
pchengzhwang

pchengzhwang@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
在2019年3月25日 10:05，yimelia<notifications@github.com><mailto:notifications@github.com> 写道：

当前最新版本的IDE尚未更新，如果使用了本地poco可以更新到最新版本就可以直接 .parent()。
如果只使用IDE的话可以稍等下，本周我们很快会放出一个新版本的IDE的。
