### ISSUE TITLE
test-flow自动安装pocoservice，无法点击授权框

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Poco#28]
现在testflow自己安装卸载 pocosrevice ，也会弹出授权框，手机没法点击过去。
这个在那里修改呀。
我安装自己的应用都是用adb shell install，然后检查是否有弹出框，手动点击的。
![tim 20180606100152](https://user-images.githubusercontent.com/38519076/41011824-427e44fe-6971-11e8-8abe-1db69e3bb488.png)

**Comment by adolli** [comment]
这个只能在你手机里手动关闭usb安装验证了。不同型号手机的设置位置都不一样，请麻烦到处找找“安全设置”、“开发者设置”之类的选项。

**Comment by adolli** [comment]
这个跟系统无关，跟手机厂的android定制有关，需根据手机对应的来设置。

**Comment by bs111** [comment]
嗯 好的，和开发确认过了
搞定了
tks
