### ISSUE TITLE
 airtest.core.error.AdbError: stdout[] stderr[error: cannot rebind existing socket

### ISSUE THREAD

**Issue by agoraHan** [AirtestProject/Poco#282]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

```
（在这里粘贴traceback或其他报错信息）
```
common/maincase.py:26: in inputChannelName
    touch(Template(r"resource/images/tpl1569122471940.png", record_pos=(-0.071, 0.076), resolution=(1080, 2280)))
../Library/Python/3.6/lib/python/site-packages/airtest/utils/logwraper.py:78: in wrapper
    res = f(*args, **kwargs)
../Library/Python/3.6/lib/python/site-packages/airtest/core/api.py:257: in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
../Library/Python/3.6/lib/python/site-packages/airtest/utils/logwraper.py:78: in wrapper
    res = f(*args, **kwargs)
../Library/Python/3.6/lib/python/site-packages/airtest/core/cv.py:59: in loop_find
    screen = G.DEVICE.snapshot(filename=None)
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/android.py:218: in snapshot
    screen = self.minicap.get_frame_from_stream()
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/minicap.py:24: in wrapper
    return func(inst, *args, **kwargs)
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/minicap.py:339: in get_frame_from_stream
    self.frame_gen = self.get_stream()
../Library/Python/3.6/lib/python/site-packages/airtest/utils/snippet.py:106: in ready_func
    return func(inst, *args, **kwargs)
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/minicap.py:233: in get_stream
    stopped = next(gen)
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/minicap.py:247: in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/minicap.py:300: in _setup_stream_server
    localport, deviceport = self.adb.setup_forward("localabstract:minicap_{}".format)
../Library/Python/3.6/lib/python/site-packages/airtest/utils/retry.py:46: in f2
    return func(*args, **kwargs)
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/adb.py:515: in setup_forward
    self.forward("tcp:%s" % localport, device_port)
../Library/Python/3.6/lib/python/site-packages/airtest/core/android/adb.py:459: in forward
    self.cmd(cmds + [local, remote])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <airtest.core.android.adb.ADB object at 0x11abeaa20>, cmds = ['forward', '--no-rebind', 'tcp:11589', 'localabstract:minicap_11589'], device = True
ensure_unicode = True

    def cmd(self, cmds, device=True, ensure_unicode=True):
        """
            Run the adb command(s) in subprocess and return the standard output
    
            Args:
                cmds: command(s) to be run
                device: if True, the device serial number must be specified by -s serialno argument
                ensure_unicode: encode/decode unicode of standard outputs (stdout, stderr)
    
            Raises:
                DeviceConnectionError: if any error occurs when connecting the device
                AdbError: if any other adb error occurs
    
            Returns:
                command(s) standard output (stdout)
    
            """
        proc = self.start_cmd(cmds, device)
        stdout, stderr = proc.communicate()
    
        if ensure_unicode:
            stdout = stdout.decode(get_std_encoding(sys.stdout))
            stderr = stderr.decode(get_std_encoding(sys.stderr))
    
        if proc.returncode > 0:
            # adb connection error
            pattern = DeviceConnectionError.DEVICE_CONNECTION_ERROR
            if isinstance(stderr, binary_type):
                pattern = pattern.encode("utf-8")
            if re.search(pattern, stderr):
                raise DeviceConnectionError(stderr)
            else:
>               raise AdbError(stdout, stderr)
E               airtest.core.error.AdbError: stdout[] stderr[error: cannot rebind existing socket
E               ]

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python3.6`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [华为nova 3e]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
在AirtestIDE运行正常 
pycharm脚本运行报错

测试脚本：
在
start_app()
poco("XXX").click()之后报错

**Comment by yimelia** [comment]
把脚本内容贴出来看看，这个报错信息太过于混乱了

看提示可能是有端口占用的问题，退出游戏，退掉IDE，保持环境干净的情况下运行脚本，并且确认**先start_app之后，再初始化poco对象**，然后再往下继续调用。
