### ISSUE TITLE
更新了最新版ide，但是poco语句老是运行失效

### ISSUE THREAD

**Issue by appp-deng** [AirtestProject/Poco#288]
就比如poco(text="点击登录").click()这一句，右侧屏幕可以看到“点击登录”。但是运行时这句代码却没有生效，标亮条直接从这一句跳到下一句却没有跳到登录页面，导致下一句代码运行出错，重新运行这句代码又有效了。

**Comment by yimelia** [comment]
请补充更加完善的信息：
1. ”更新了最新版IDE“，是否旧版IDE里能够正常运行？请列出具体的版本号
2. 请生成运行结果报告，并且查看这一句语句的运行结果，是否已经成功点击到了对应的控件？
3. 如果报告中显示已经成功点击到对应的按钮，但是实际上没有成功运行，可以在运行到这一句代码之前，进行一些适当的sleep，确保手机运行到这个画面停留了一定时间后再进行点击，因为有些手机可能因为卡顿或者是画面跳转过快，导致虽然点击了对应坐标，但是实际上手机画面还未完全稳定下来，导致没成功点击到控件

**Comment by yimelia** [comment]
参考文档：https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#6-airtestsleep

**Comment by appp-deng** [comment]
> 请补充更加完善的信息：
> 
> 1. ”更新了最新版IDE“，是否旧版IDE里能够正常运行？请列出具体的版本号
> 2. 请生成运行结果报告，并且查看这一句语句的运行结果，是否已经成功点击到了对应的控件？
> 3. 如果报告中显示已经成功点击到对应的按钮，但是实际上没有成功运行，可以在运行到这一句代码之前，进行一些适当的sleep，确保手机运行到这个画面停留了一定时间后再进行点击，因为有些手机可能因为卡顿或者是画面跳转过快，导致虽然点击了对应坐标，但是实际上手机画面还未完全稳定下来，导致没成功点击到控件

加了sleep（）好像可以了，谢谢
