### ISSUE TITLE
将unity3d文件夹复制进目录，报ugui/unitynode.cs多个重复定义

### ISSUE THREAD

**Issue by Ruyannn** [AirtestProject/Poco#289]
**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
将unity3d文件夹复制进目录，报错ugui/unitynode.cs的namespace Poco 有多个重复定义
(详情看下方截图)

```
（在这里粘贴traceback或其他报错信息）
```

**复现步骤**
1. 复制unity3d文件夹
2. 删除/ngui
3. 报错

**预期效果**
（这个应该不会报错吧）

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
报错截图：
![image](https://user-images.githubusercontent.com/56384751/66548285-8e23fb80-eb73-11e9-99b5-39d26ff225ff.png)
目录截图：
![image](https://user-images.githubusercontent.com/56384751/66548410-cd524c80-eb73-11e9-9202-595a5e17fdbc.png)

**python 版本:** `python2.7`

**poco 版本:** `1.0.78`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: pc
 - 系统: win10
 - (别的信息)

**其他相关环境信息**
win10

**Comment by yimelia** [comment]
可以参考这个文档： https://airtest.doc.io.netease.com/tutorial/11_如何测试基于Unity3D引擎的游戏/

将Assets/Scripts/Unity3D目录下以未用到的UI系统命名的文件夹删除。例：假如您的项目使用的UI系统是ugui，请将fairygui和ngui两个文件夹删除，保留ugui文件夹。

**Comment by Ruyannn** [comment]
> 可以参考这个文档： [https://airtest.doc.io.netease.com/tutorial/11_如何测试基于Unity3D引擎的游戏/](https://airtest.doc.io.netease.com/tutorial/11_%E5%A6%82%E4%BD%95%E6%B5%8B%E8%AF%95%E5%9F%BA%E4%BA%8EUnity3D%E5%BC%95%E6%93%8E%E7%9A%84%E6%B8%B8%E6%88%8F/)
> 
> 将Assets/Scripts/Unity3D目录下以未用到的UI系统命名的文件夹删除。例：假如您的项目使用的UI系统是ugui，请将fairygui和ngui两个文件夹删除，保留ugui文件夹。

已解决~小白叩谢
