### ISSUE TITLE
关于多脚本运行报告的建议

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Poco#290]
@yimelia 
我创建了10个.air脚本，分别运行它们后，每一个.air目录下都有一份报告，查阅比较麻烦，有没有办法将所有air的执行结果汇总到一份html，在这个html里有每个air的执行结果（如果多设备运行同一份air，有任意设备失败就显示失败）和详细报告的链接

**Comment by EraChen233** [comment]
多机运行可以参考这个
http://git-qa.gz.netease.com/maki/airtest-multi-cli
另外我们现在在推小型机柜，里面的系统包括你想要的报告，如果有兴趣，可以加我们QQ群私聊
AirtestProject讨论2群 1017250147
