### ISSUE TITLE
airTest IDE生成path，执行报语法错误

### ISSUE THREAD

**Issue by happyMeiyo** [AirtestProject/Poco#295]
**描述问题bug**
右键组件，单击“UI path-code”，airTest IDE生成path，但是执行脚本报语法错误

![image](https://user-images.githubusercontent.com/22342835/66814424-26055900-ef69-11e9-97a0-696af2cfdf81.png)

**Comment by yimelia** [comment]
一般情况下，这是脚本里有语法错误，例如缩进错误、拼写错误等，如果不贴出脚本全文的话，我们看不出是什么问题。
不过，我建议你先自己找一下看看，可能是上下两行之间的缩进有问题。

**Comment by happyMeiyo** [comment]
你好，这是脚本全文 @yimelia 

```python
# -*- encoding=utf8 -*-
__author__ = "Administrator"

from airtest.core.api import *

# script content
print("start...")

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

auto_setup(__file__)

poco(poco("com.caibaopay.cashier:id/rl_take_order").click()
     poco("android.widget.LinearLayout").offspring("android:id/content").child("android.widget.LinearLayout").offspring("com.caibaopay.cashier:id/fl_container").child("android.widget.LinearLayout").offspring("com.caibaopay.cashier:id/fl_right").offspring("com.caibaopay.cashier:id/rlv_order_list").child("com.caibaopay.cashier:id/ll_root")[0].child("android.widget.LinearLayout").child("android.widget.LinearLayout").offspring("com.caibaopay.cashier:id/ftv_amount").get_text()
    
```

**Comment by yimelia** [comment]
![image](https://user-images.githubusercontent.com/6896468/66820241-e17ebb00-ef72-11e9-8306-a1f751da944a.png)

这里多了一个缩进

**Comment by happyMeiyo** [comment]
![image](https://user-images.githubusercontent.com/22342835/66823883-ac299b80-ef79-11e9-9cab-fec116ba376d.png)
好诡异呀，在编辑器没有缩进。我反复删除缩进很多次，还是报语法错误

**Comment by happyMeiyo** [comment]
问题解决了，谢谢。
![image](https://user-images.githubusercontent.com/22342835/66881568-d6bb3900-eff9-11e9-8ff7-aaa1d3eacd76.png)
