### ISSUE TITLE
【请教】MuMu模拟器，EditView类型的widget无法输入

### ISSUE THREAD

**Issue by happyMeiyo** [AirtestProject/Poco#299]
**描述问题bug**
连接MuMu模拟器，通过shell()和text()的方法，EditView类型的widget无法输入文本。

**测试页面**
![image](https://user-images.githubusercontent.com/22342835/66987232-eff3e080-f0f2-11e9-9e9a-99a9e05080fc.png)

**组件属性**
![image](https://user-images.githubusercontent.com/22342835/66986938-588e8d80-f0f2-11e9-8503-8810bc4df147.png)

**MuMu模拟器连接**
```python
connect_device("Android://127.0.0.1:5037/127.0.0.1:7555?ime_method=ADBIME&cap_method=JAVACAP&ori_method=ADBORI")
```

**测试代码**
```python
    def test_temporaryGoods(self):
        # %% 加购临时商品

        time.sleep(5)

        self.poco(text="临时商品").swipe([-0.5712, 0.0439])
        self.poco(text="临时商品").click()
        self.poco(text="临时商品_计件").click()

        time.sleep(2)

        self.poco("com.caibaopay.cashier:id/tv_sale_price").setattr(text, '10.00')

        self.poco("com.caibaopay.cashier:id/tv_sale_price").click()
        shell("input text '12.00'")

        self.poco("com.caibaopay.cashier:id/tv_number").click()
        text("12")

        time.sleep(2)

        # %%

        self.poco("com.caibaopay.cashier:id/tv_confirm").click()
```

**测试执行脚本**
![image](https://user-images.githubusercontent.com/22342835/66987093-a99e8180-f0f2-11e9-910d-74e9d52fc1a8.png)

**执行结果**
零售价和数量未输入
![image](https://user-images.githubusercontent.com/22342835/66987356-347f7c00-f0f3-11e9-8561-40334ad1128e.png)

**python 版本:** `python 3.6.4`

**poco 版本:** `1.0.78`

**MuMu模拟器设置**
![image](https://user-images.githubusercontent.com/22342835/66987599-aeb00080-f0f3-11e9-9701-1157a54b3a6b.png)

![image](https://user-images.githubusercontent.com/22342835/66987663-ca1b0b80-f0f3-11e9-87c8-21989f01313a.png)

**Comment by yimelia** [comment]
可能是程序做了限制，特殊的输入框不允许直接修改值或者接受键盘输入，只能去点弹出的那个键盘里的内容。
可以试一下去点弹出式键盘里的数字来进行输入，或者是用图像识别的方式去点击
