### ISSUE TITLE
cocos太低，两个文件差异性太大，没发接pocoSDK

### ISSUE THREAD

**Issue by zhaoxianning** [AirtestProject/Poco#30]
[libwebsockets.txt](https://github.com/AirtestProject/Poco/files/2088524/libwebsockets.txt)
[libwebsockets_airtest.txt](https://github.com/AirtestProject/Poco/files/2088525/libwebsockets_airtest.txt)

PS：后缀名是  （.h）,上传的时候不支持改格式改成txt了

**Comment by adolli** [comment]
版本低的cocos里，libwebsocket_server和libwebsocket_client只能二选一了，cocos里默认带有的是libwebsocket_client，如果要加入libwebsocket_server模块，需要把libwebsocket_client相关的源码都移除。

**Comment by zhaoxianning** [comment]
我这个是单机游戏，需要接入web_socket 的东西

**Comment by adolli** [comment]
因为poco-sdk需要在游戏内启动一个server，然后poco与这个server通信来达到跟游戏通信的效果，因此libwebsocket_server这个模块是需要的。

**Comment by adolli** [comment]
你可以自己reopen这个issue，如果你需要的话
