### ISSUE TITLE
请问cocos creator开发的项目可以用poco么，如果可以有相关的操作步骤么

### ISSUE THREAD

**Issue by abcdd12** [AirtestProject/Poco#307]
请问cocos creator开发的项目可以用poco么，如果可以有相关的操作步骤么

**Comment by yimelia** [comment]
cocos creator的支持即将外放，更新后我们会同步到这里，后续关注这个帖子即可

**Comment by Linzecong** [comment]
已经发布，详见 [https://poco.readthedocs.io/en/latest/source/doc/integration.html#cocos-creator](https://poco.readthedocs.io/en/latest/source/doc/integration.html#cocos-creator)
