### ISSUE TITLE
cocos太低，两个文件差异性太大，没发接pocoSDK

### ISSUE THREAD

**Issue by zhaoxianning** [AirtestProject/Poco#31]
[libwebsockets_airtest.txt](https://github.com/AirtestProject/Poco/files/2088627/libwebsockets_airtest.txt)
[libwebsockets.txt](https://github.com/AirtestProject/Poco/files/2088628/libwebsockets.txt)
不好意思，刚才那个问题不小心给关了，

**Comment by adolli** [comment]
#30 duplicate
