### ISSUE TITLE
在IDE里面能运行的python代码单独调用运行失败

### ISSUE THREAD

**Issue by primejava** [AirtestProject/Poco#311]
**描述问题bug**
控件点击失败,代码如下,非常简单的点击某坐标位置的按钮
`touch((612,1215),1)`

```
RuntimeError: minicap server setup timeout
```

**预期效果**
希望能够成功的点击按钮

**python 版本:** `python3.7`

**poco 版本:** `1.0.78`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 系统: MIUI11
 - (别的信息)

**其他相关环境信息**
在IDE上运行正常

**Comment by yimelia** [comment]
duplicate of https://github.com/AirtestProject/Airtest/issues/504
MIUI11是安卓10的，minicap暂时还没有兼容。
本帖内容重复，我关闭了，请关注上面这个issue来获得最新进展
