### ISSUE TITLE
安卓机刘海屏UI识别位置与实际位置有偏差，导致部分操作在unityEdity中操作正常，在安卓机上不能正确点击UI

### ISSUE THREAD

**Issue by weixiaovision** [AirtestProject/Poco#316]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
安卓机刘海屏UI识别位置与实际位置有偏差，导致部分操作在unityEdity中操作正常，在安卓机上不能正确点击UI
```
（在这里粘贴traceback或其他报错信息）
```

**复现步骤**
1. 根据控件名称点击邮件按钮
2. poco("BtnMail").click()
3.会点击到游戏可操作范围外的区域，导致点击按钮没有效果

**预期效果**
请问可以有什么好的办法适配此类机型吗
**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![image](https://user-images.githubusercontent.com/27843241/69708584-d94f9900-1136-11ea-978d-b39051ac1232.png)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [华为 Honor 10]
 - 系统: [Android 9]
 - (别的信息)
所有的控件位置信息与实际信息都是有偏差的
![image](https://user-images.githubusercontent.com/27843241/69708953-7dd1db00-1137-11ea-8035-c0b93558e487.png)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by EraChen233** [comment]
更新最新IDE
https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#3
