### ISSUE TITLE
UI定位有时会出现偏移

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Poco#319]
@yimelia 
使用设备VIVO X23（安卓版本8.1.0）
在AirtestIDE定位控件的时候，有时会出现偏移，具体见下图
左边是AirtestIDE中定位返回按钮，但是它定位的区域明显偏离了按钮的响应区
右边是在Unity中该按钮的位置，和AirtestIDE对比也能发现有偏移
想问下为什么会出现这种情况，有什么比较好的解决方法，谢谢
![image](https://user-images.githubusercontent.com/26775694/70140013-c573dc00-16ce-11ea-8a78-c4d1921473d8.png)

**Comment by yimelia** [comment]
是否是全面屏手机？
可以参考一下这个文档：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#3
