### ISSUE TITLE
PocoService 无法运行：此应用专为旧版 Android 打造，因此可能无法正常运行。

### ISSUE THREAD

**Issue by LoveOctocat** [AirtestProject/Poco#321]
**描述问题bug**
PocoService 无法运行，同时提示：
此应用专为旧版 Android 打造，因此可能无法正常运行。请尝试检查更新或与开发者联系。

**相关截图**
![WechatIMG103](https://user-images.githubusercontent.com/19794638/70234372-7b0c6100-179b-11ea-91d6-6a28e675b5b6.jpeg)

**poco 版本:** `1.0.0.41`

**设备:**
 - 型号: Oneplus 7 Pro
 - 系统: Android 10

![WechatIMG104](https://user-images.githubusercontent.com/19794638/70234412-90818b00-179b-11ea-8b02-1c21bc6fcd77.jpeg)

**Comment by yimelia** [comment]
我们将会尽快提升pocoservice.apk的版本号，请继续关注这个issue

**Comment by 2004021099** [comment]
对Android10都不兼容，这是非常影响使用的~

**Comment by yimelia** [comment]
@2004021099 
没有不兼容，是可用的，只是会有这个提示而已

**Comment by TimsXH** [comment]
请问这个问题修复了吗~~~~因为我今天又遇到了

**Comment by gzhtest** [comment]
你们的是不是也是不断重启重装，然后要手动启动下才行。
