### ISSUE TITLE
在分屏模式下，将操作切换至不同分屏失败

### ISSUE THREAD

**Issue by vip68** [AirtestProject/Poco#322]
**你遇到了什么我们这个库解决不了的问题？**

红米note7（MIUI11）分屏模式下使用poco，
1）对其中一个分屏（位于屏幕下方，分屏1）内的应用操作成功，完成预期效果
2）使用adb.start_shel()对另一个分屏（位于屏幕上方，分屏2）内的应用进行操作也是成功的，完成预期效果
3）想再次对位于下方的分屏1进行操作，却发现poco已经控制不到这个分屏了，只能对分屏2进行操作
4）尝试通过按HOME键返回桌面，再次打开分屏1内的应用，继续运行poco，这才能识别到分屏1，才能执行成功
5）此问题不是必现，但十次可能有九次会遇到。每次在分屏1切换到分屏2操作后，必须HOME键返回桌面，才能够识别分屏2，极其不便

**描述一下你想如何解决这个问题**

期待能够解决此问题，能够实现切换分屏

**额外信息**

红米note7（Android9，MIUI11.0.3）

**Comment by vip68** [comment]
我已经自行解决

**Comment by yimelia** [comment]
可以考虑将解决方案发上来，后续其他人可以作为参考~
