### ISSUE TITLE
unity2017.4.34f1，文本插件用的TextMeshProUGUI，poco的gettext返回none

### ISSUE THREAD

**Issue by jilvtianya** [AirtestProject/Poco#324]
unity2017.4.34f1，文本插件用的TextMeshProUGUI，poco的gettext返回none.
请问如何解决

**Comment by dinghongyi** [comment]
gettext()获取的是类型为Text的Gameobject。

**Comment by dinghongyi** [comment]
gettext()获取的是类型为Text的GameObject。
你需要的类型是TMP_Text。
可以仿照 https://forum.unity.com/threads/access-textmeshpro-text-through-script.527992/ 在ugui/UnityNode.cs中修改/添加对应的支持。

**Comment by jilvtianya** [comment]
搞定了，多谢
