### ISSUE TITLE
滑动页面后出现的控件无法识别

### ISSUE THREAD

**Issue by liyc9** [AirtestProject/Poco#326]
**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
想要的控件需进行滑动后才能出现，但是滑动页面后出现的控件无法识别出来
```
（在这里粘贴traceback或其他报错信息）
```

**复现步骤**
下面是代码
while  not poco(name="智能组合").exists():
    swipe([500,2300],[500,1000])
    sleep(1)
else:
    poco(name="智能组合").click()
1. 检测控件是否存在
2. 不存在则进行滑动
3. 存在则点击

**预期效果**
能够点击智能组合控件

**相关截图**
现在会一直陷入第一段循环一直滑动页面无法识别控件

**python 版本:** `python3.6`

**poco 版本:** `1.0.78`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [华为荣耀V9]
 - 系统: [e.g. Android 9.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by EraChen233** [comment]
麻烦尽量提供截图
滑动后的页面，IDE可以识别出你要的控件吗？

**Comment by liyc9** [comment]
就是在IDE运行，无法识别到该控件

**Comment by EraChen233** [comment]
我们这边暂时没出现这种情况哦，所以麻烦提供详细信息让我们复现，不然没有办法定位问题呢
