### ISSUE TITLE
poco不支持iOS平台了么？

### ISSUE THREAD

**Issue by gaoliaaa** [AirtestProject/Poco#329]
在http://airtest.netease.com/docs/cn/6_poco_framework/poco_quick_start.html#id2文档中，iOS平台对应的poco帮助文档链接404。
是否是不支持了？iOS应该如何导入呢？

**Comment by yimelia** [comment]
换地址了：https://airtest.doc.io.netease.com/IDEdocs/device_connection/4_ios_connection/
