### ISSUE TITLE
pycharm导入iosPoco报错

### ISSUE THREAD

**Issue by gaoliaaa** [AirtestProject/Poco#330]
**描述问题bug**
在pycharm中，from poco.drivers.ios import iosPoco报错。

<img width="764" alt="image" src="https://user-images.githubusercontent.com/41134094/71475422-23ea3100-281b-11ea-83b5-31f73d6f92a0.png">

**python 版本:** `python2.7`

**poco 版本:** 1.0.78

**Comment by EraChen233** [comment]
试一下在这个环境重新安装poco吧
![image](https://user-images.githubusercontent.com/5961185/71496543-c8598b00-288e-11ea-80d4-2ad487d6daf8.png)

**Comment by gaoliaaa** [comment]
> 试一下在这个环境重新安装poco吧
> ![image](https://user-images.githubusercontent.com/5961185/71496543-c8598b00-288e-11ea-80d4-2ad487d6daf8.png)

可以了谢谢！因为在之前复制AirtestIDE中的代码到Pycharm的时候，有包的报错，误点了安装"poco"包，再后续安装了“pocoui”包之后，因为识别问题所以报了上述错误。在卸载掉“poco”“pocoui”，重新安装“pocoui”之后成功。
