### ISSUE TITLE
请问有推荐的Android 手机系列，我这里计划采购一批Android设备。

### ISSUE THREAD

**Issue by xifarm** [AirtestProject/Poco#332]
请问，有无推荐的Android设备型号列表，即可以识别UI树的，我这里计划采购一批Android设备。

价格500元左右。

**Comment by xifarm** [comment]
Android Native APP.

**Comment by EraChen233** [comment]
推荐华为、三星、小米，oppo 和 vivo 安装需要密码，在测试的时候可能会麻烦。根据自己做决定吧
