### ISSUE TITLE
项目引擎版本为Cocos2dx-lua 2.x版本，poco框架要求版本 >= 3.1，有办法解决么？

### ISSUE THREAD

**Issue by jiangfangjian** [AirtestProject/Poco#333]
**你遇到了什么我们这个库解决不了的问题？**
项目引擎版本为Cocos2dx-lua 2.x版本，poco框架要求版本 >= 3.1。开发组后续会提供支持么？如果不会的话，可以有什么办法自己改么？

**Comment by EraChen233** [comment]
短期内可能不会做这方面的支持，Poco是开源的，可以参考其他引擎的使用方式自行修改代码

**Comment by jiangfangjian** [comment]
好的，谢谢
