### ISSUE TITLE
想要注册Unity游戏内的接口供脚本调用

### ISSUE THREAD

**Issue by terieqin** [AirtestProject/Poco#334]
我尝试通过现有的RPC去调用SDK里面已经注册的方法：
```python
from poco.drivers.unity3d import UnityPoco
import airtest

poco = UnityPoco()
size = poco.agent.rpc.call("GetScreenSize")
print(size)
```
但是返回给我的是一个CallBack的对象。请问我要怎么正确使用这个RPC呢？

**Comment by terieqin** [comment]
我发现unity3d_poco.py里，第21行，返回给suport_vr的值也是CallBack对象。这样真的可以解析出什么信息吗？

**Comment by q287524305** [comment]
我也遇到了这个问题 但是网易为啥不给出解决方案 源码里也没有关于callback的解答

**Comment by flypart** [comment]
结尾加上.wait()就可以了。例如：
r = poco.agent.rpc.call("GetScreenSize").wait()
print(r)
详见类：utils/simplerpc/simplerpc.py
