### ISSUE TITLE
获取组件上的属性

### ISSUE THREAD

**Issue by terieqin** [AirtestProject/Poco#336]
**你遇到了什么我们这个库解决不了的问题？**
我想要获取某个组件上的属性。需求来源于游戏中某些控件上的图片是由一个自定义（扩展原生）的组件控制的，我希望能够通过获取图片的名称来判断我应该点击哪个控件。

**描述一下你想如何解决这个问题**
之前Tencent的GAutomator提供的SDK里面是通过反射的方式获取的。详情可参考U3DAutomation.CommandHandler.handleGetObjectField()。

**额外信息**
无

**Comment by EraChen233** [comment]
https://poco-chinese.readthedocs.io/zh_CN/latest/source/README.html#get-object-properties
