### ISSUE TITLE
希望能支持H5控件的识别

### ISSUE THREAD

**Issue by NanYeYe** [AirtestProject/Poco#337]
移动设备H5页面的元素，无法识别

还有微信小程序，是不是实际上也是不支持呢
![image](https://user-images.githubusercontent.com/11953895/72047364-53a63800-32f5-11ea-9e8c-6f1076ec6d61.png)

![image](https://user-images.githubusercontent.com/11953895/72047420-6f114300-32f5-11ea-8df5-46bcc159fbf1.png)

**Comment by yimelia** [comment]
我这里试过很多APP上的H5页面是支持的，具体是否支持，需要你自己用一下才知道，选择Android-poco然后看看能否出UI树。
