### ISSUE TITLE
poco.exists和poco.click()太耗时

### ISSUE THREAD

**Issue by terieqin** [AirtestProject/Poco#338]
**你遇到了什么我们这个库解决不了的问题？**
普通攻击释放过程中，比如有普1，普2， 普3。。。普1释放之后必须在很短的时间内再点击普通攻击才能释放普2。然而，poco的点击太慢，每次获取控件都需要dump整个树下来，每次点击都要获取一次控件。在战斗场景中，一次点击函数甚至耗时2000ms。

我希望有一种方式，能够获取控件的时候只拿它一个控件的信息，然后点击的时候就点击它就好了。

poco().click之前都需要poco().exists()来判断控件是否存在，否则会抛出异常。然而有些技能CD很短，上一秒判断poco().exists()得到技能控件存在，下一秒poco().click()就不存在了，又抛出异常。显然脚本执行click()期间，游戏已经过去几十帧了，在这种快节奏的游戏下，poco().exists()有点形同虚设。

**描述一下你想如何解决这个问题**
比如poco("Button")我只从C#层返回符合这个query的信息，包括它的坐标。然后poco("Button").click()点击坐标即可。

**额外信息**
(运行环境、设备、相关参考信息，如果有的话。)

**Comment by yimelia** [comment]
1. 可以参考一下poco的UI冻结功能：https://poco-chinese.readthedocs.io/zh_CN/latest/source/doc/poco-example/optimize_speed_by_freezing_UI.html

2. 如果UI变化很快的话，不建议用过多的自动化
