### ISSUE TITLE
可以在一个测试里用两种driver吗，比如我有个Unity的游戏，但是登陆时要用Android原始driver。

### ISSUE THREAD

**Issue by goodking-bq** [AirtestProject/Poco#341]
可以在一个测试里用两种driver吗，比如我有个Unity的游戏，但是登陆时要用Android原始driver。
现在是我先初始化UnityPoco没问题，但是到初始化AndroidUiautomationPoco时，pocoservice会报错
`
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
[pocoservice.apk] stderr: b''
`

**Comment by LRL2018** [comment]
我也遇到这个问题了，先用的AndroidUiautomationPoco处理安装权限，然后进入Unity游戏后用的UnityPoco， 但是一直报这个错，现在还没解决，，请问你解决了嘛
