### ISSUE TITLE
自动化测试脚本采用华为p20进行执行，执行过程中会出现以下问题

### ISSUE THREAD

**Issue by wqfff** [AirtestProject/Poco#345]
我用的是华为p20执行自动化测试脚本，开始执行时能够正常运行，但是运行一段时间会出现以下问题，请问出现以下问题该如何解决：

相关截图
![image](https://user-images.githubusercontent.com/55772937/74116443-88582880-4bee-11ea-808b-2958760fb33c.png)

python 版本: python3.6.8

poco 版本: 1.0.78

设备:

型号:华为P20
系统: Android 8.0
其他相关环境信息
Mac OS  10.14 上运行异常

**Comment by yimelia** [comment]
有可能是手机自动把pocoservice的进程给清理掉了，可以参考一下文档里面的华为手机第五点：https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_6
试着修改一下pocoservice两个apk的权限看看
