### ISSUE TITLE
使用控件树快速获取UI路径，但是获得的路径有多余的部分

### ISSUE THREAD

**Issue by 307060090** [AirtestProject/Poco#351]
@yimelia 
为什么在控件树上右键快速获取UI路径的时候，再最末尾会多了一个序号，具体如下图
有些控件就不会出现这个问题

![TIM图片20200225160149](https://user-images.githubusercontent.com/61450561/75226950-374c5500-57e8-11ea-8475-3e85deb68b60.png)

**Comment by yimelia** [comment]
自动生成的语句不一定准确，建议在编写代码时最好人工复核一遍
