### ISSUE TITLE
poco wait_for_appearance()函数失效

### ISSUE THREAD

**Issue by yuzhujiutian** [AirtestProject/Poco#36]
try:
    poco('Button_11', type='Button').wait_for_appearance()
    print('aaa')
except PocoTargetTimeout:
    print('bbb')
    raise    # bugs here as the panel not show
print('ccc')

部分代码块如上，执行 wait_for_appearance() 语句之前，该界面还没有出来（例如刚启动app），但在这30秒之内（例如15s左右）该界面能出来，

实测结果发现还是执行了timeout 即raise操作

是我对 wait_for_appearance() 理解不对后使用不对，还是当前该函数可能还需要完善？

另外，如果在执行 wait_for_appearance() 语句之前，该界面就已存在，则不会执行timeout操作

测试环境：
AirtestIDE_2018-06-19_v0.1.1_py3_win64

$ python -V
Python 3.6.5

$ pip freeze
airtest==1.0.17
apkutils==0.2.8
certifi==2018.4.16
chardet==3.0.4
cigam==0.0.3
comtypes==1.1.4
facebook-wda==0.2.1
hrpc==1.0.4
idna==2.7
Jinja2==2.10
MarkupSafe==1.0
numpy==1.14.5
opencv-contrib-python==3.2.0.7
Pillow==5.1.0
pocoui==1.0.52
pocounit==1.0.33
pyelftools==0.24
pypiwin32==223
pywin32==223
pywinauto==0.6.3
requests==2.19.1
six==1.11.0
urllib3==1.23
websocket-client==0.48.0
xmltodict==0.11.0

**Comment by yuzhujiutian** [comment]
http://poco-chinese.readthedocs.io/zh_CN/latest/source/README.html#exceptions

PocoTargetTimeout

from poco.exceptions import PocoTargetTimeout

try:
    poco('guide_panel', type='ImageView').wait_for_appearance()
except PocoTargetTimeout:
    # bugs here as the panel not shown
    raise
PocoNoSuchNodeException

from poco.exceptions import PocoNoSuchNodeException

img = poco('guide_panel', type='ImageView')
try:
    if not img.exists():
        img.click()
except PocoNoSuchNodeException:
    # If attempt to operate inexistent nodes, an exception will be thrown
    pass


这里提到的两个方法，都有这个问题。

**Comment by yuzhujiutian** [comment]
找到原因了，poco模块加载，需要放在游戏进程启动之后


# poco
from poco.drivers.std import StdPoco
poco = StdPoco()
from poco.exceptions import PocoTargetTimeout, PocoNoSuchNodeException

**Comment by Meteorix** [comment]
多谢反馈

**Comment by adolli** [comment]
@yuzhujiutian  `poco = StdPoco()`只需要把这句话放到游戏启动之后，这样才能跟poco-sdk建立连接。
