### ISSUE TITLE
请问使用crontab起定时任务比直接起任务速度慢很多是什么原因？

### ISSUE THREAD

**Issue by xgx666** [AirtestProject/Poco#362]

**Comment by yimelia** [comment]
抱歉，在现有的信息下，我们无法得知。

**Comment by xgx666** [comment]
就是直接运行.py文件速度是正常的，但是使用定时任务crontab这个命令调py脚本速度明显慢一倍。我猜测是不是因为输出日志影响了速度，然后将Airtest的默认输出到控制台的日志重定向到文件中，依然还是很慢。

**Comment by yimelia** [comment]
我们没有遇到过类似问题，请根据实际环境和信息自行调试吧，抱歉。

**Comment by xgx666** [comment]
就是直接运行.py文件速度是正常的，但是使用定时任务crontab这个命令调py脚本速度明显慢一倍。我猜测是不是因为输出日志影响了速度，然后将Airtest的默认输出到控制台的日志重定向到文件中，依然还是很慢。
