### ISSUE TITLE
如何获取长按弹出的tips信息

### ISSUE THREAD

**Issue by ymdhtt** [AirtestProject/Poco#366]
@yimelia 
游戏中有些物品icon长按会有tips信息，我该怎么获取保持长按才有的tips信息（取消长按就没有tips了）
PS：因为tips信息是在保持长按之后出现的，当我试图获取时，已经完成了长按操作，tips信息也没了

**Comment by yimelia** [comment]
目前没有现成的接口完成这件事，需要自己进行组装：
如果是windows，有一个key_press接口可以用来模拟鼠标按住，然后做其他操作即可，参考 https://airtest.doc.io.netease.com/tutorial/12_test_PCgame/
如果是android的话，可以自行封装event，参考 https://airtest.doc.io.netease.com/IDEdocs/faq/3_api_faq/#8 ，先执行downevent，然后做其他事，最后再执行一个upevent
我没有对上述设想进行过测试，仅供参考

**Comment by ymdhtt** [comment]
@yimelia ,我试了下，可以是可以，但是你说的方法是获取设备的竖屏坐标，如果在不同的设备上运行，这个坐标恐怕会变

**Comment by yimelia** [comment]
请结合实际情况来修改你的代码，文档只是给出一个范例，没有让你直接写死坐标
你可以先调 exists来获取坐标，然后后续再进行点击啊

**Comment by ymdhtt** [comment]
明白了，感谢解答

**Comment by ymdhtt** [comment]
@yimelia ,你提供的DownEvent，UpEvent方式在Airtest IDE 1.2.2.版本可以用
但是我用python拉取最新的airtest库（1.1.3版本），airtest.core.android.minitouch这个库里没有DownEvent，UpEvent等相关信息，我比对了AirtestIDE和python拉下来的库，airtest.core.android.minitouch库文件内容不一样

**Comment by yimelia** [comment]
是啊，最新版改了代码位置，换个import位置不就行了
