### ISSUE TITLE
页面中部分UI布局改变，获取新的UI元素的text属性却还是改变前UI元素的text

### ISSUE THREAD

**Issue by daichengxmu** [AirtestProject/Poco#368]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
我在开发APP爬虫，需要获取有关控件的text属性。在某一个页面中有几个选项卡，点击不同选项卡后下面的UI元素也会对应改变，但是布局很类似。我在点击新选项卡后想获取下面控件的text属性，但是返回的是之前选项卡下面对应位置的控件的text属性。

**复现步骤**

**预期效果**
希望新选项卡下面控件的text属性能够和当前页面对应上

**相关截图**
![image](https://user-images.githubusercontent.com/41791412/77512889-d8ddc980-6eae-11ea-91a4-e1f5375cfda9.png)
![image](https://user-images.githubusercontent.com/41791412/77512996-10e50c80-6eaf-11ea-95c1-3fa358b82679.png)
我希望获取红框标注区域的文本，第二张截图为切换到第二个选项卡后页面更新了，但是第一个红框标注区域的UI元素获取其text属性却还是第一个选项卡中第一个红框内的text，第二个红框内的text对应正确。看起来像是UI属性没有全部更新过来的样子。

**python 版本:** `python3.6`

**poco 版本:** `1.0.79`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: ONEPLUS A5000
 - 系统: Android 9

**其他相关环境信息**
无

**Comment by yimelia** [comment]
贴出你的代码

**Comment by daichengxmu** [comment]
> 贴出你的代码
以下代码中product_name即是出问题的地方，它打印出第一个选项卡对应位置控件的text

banks_widget = poco("allCard").child("android.view.View")[0]
    bank_widget_list = banks_widget.child("android.widget.ListView")[0].child("android.view.View")
    num_banks = len(bank_widget_list)
    bank_info_list=[]
    for i in range(num_banks):
        bank_widget = bank_widget_list[i]
        bank_name = bank_widget.child("android.view.View")[0].get_text()
        print("银行:%s" % bank_name)
        if bank_name in {"招行", "交行"}:
            print("跳过")
            continue
        bank_widget.click()
        # time.sleep(0.5)
        if poco(text="更多信息").exists():
            poco(text="更多信息").click()
            # time.sleep(0.5)
        view_widget_list = poco("allCard").child("android.view.View")
        print("num of products:%d" % (len(view_widget_list) - 2))
        i=1
        product_info_list=[]
        while i<len(view_widget_list) - 1:
            bank_widget.click()
            # time.sleep(0.5)
            if poco(text="更多信息").exists():
                poco(text="更多信息").click()
                # time.sleep(0.5)
            view_widget_list = poco("allCard").child("android.view.View")
            # poco("allCard").child("android.view.View").invalidate()
            # view_widget_list = poco("allCard").child("android.view.View")
            product_widget = view_widget_list[i]
            try:
                while product_widget.attr("pos")[1] > 0.8:
                    poco.swipe([0.5, 0.7], [0.5, 0.5])
                    view_widget_list = poco("allCard").child("android.view.View")
                    product_widget = view_widget_list[i]
            except IndexError:
                break
            # product_widget.child("android.view.View").child("android.view.View")[0].invalidate()
            product_name = product_widget.child("android.view.View").child("android.view.View")[0].get_text()
            product_valid_info = product_widget.child("android.view.View").child("android.view.View")[-1].child("android.view.View")[0].get_text()
            print("产品名:" + product_name)
            print("有效时间:" + product_valid_info)

**Comment by daichengxmu** [comment]
> 贴出你的代码
banks_widget = poco("allCard").child("android.view.View")[0]
    bank_widget_list = banks_widget.child("android.widget.ListView")[0].child("android.view.View")
    num_banks = len(bank_widget_list)
    bank_info_list=[]
    for i in range(num_banks):
        bank_widget = bank_widget_list[i]
        bank_name = bank_widget.child("android.view.View")[0].get_text()
        print("银行:%s" % bank_name)
        if bank_name in {"招行", "交行"}:
            print("跳过")
            continue
        bank_widget.click()
        # time.sleep(0.5)
        if poco(text="更多信息").exists():
            poco(text="更多信息").click()
            # time.sleep(0.5)
        view_widget_list = poco("allCard").child("android.view.View")
        print("num of products:%d" % (len(view_widget_list) - 2))
        i=1
        product_info_list=[]
        while i<len(view_widget_list) - 1:
            bank_widget.click()
            # time.sleep(0.5)
            if poco(text="更多信息").exists():
                poco(text="更多信息").click()
                # time.sleep(0.5)
            view_widget_list = poco("allCard").child("android.view.View")
            # poco("allCard").child("android.view.View").invalidate()
            # view_widget_list = poco("allCard").child("android.view.View")
            product_widget = view_widget_list[i]
            try:
                while product_widget.attr("pos")[1] > 0.8:
                    poco.swipe([0.5, 0.7], [0.5, 0.5])
                    view_widget_list = poco("allCard").child("android.view.View")
                    product_widget = view_widget_list[i]
            except IndexError:
                # 优惠产品数量过多，导致滑屏后索引匹配错位，后面剩下的优惠产品通常也是无效的，因此直接忽略
                break
            # product_widget.child("android.view.View").child("android.view.View")[0].invalidate()
            product_name = product_widget.child("android.view.View").child("android.view.View")[0].get_text()
            product_valid_info = product_widget.child("android.view.View").child("android.view.View")[-1].child("android.view.View")[0].get_text()
            print("产品名:" + product_name)
            print("有效时间:" + product_valid_info)
以上代码中product_name即是出问题的地方，在外层循环第二次时，它打印出第一个选项卡下对应位置控件的text

**Comment by daichengxmu** [comment]
`banks_widget = poco("allCard").child("android.view.View")[0]
    bank_widget_list = banks_widget.child("android.widget.ListView")[0].child("android.view.View")
    num_banks = len(bank_widget_list)
    bank_info_list=[]
    for i in range(num_banks):
        bank_widget = bank_widget_list[i]
        bank_name = bank_widget.child("android.view.View")[0].get_text()
        print("银行:%s" % bank_name)
        if bank_name in {"招行", "交行"}:
            print("跳过")
            continue
        bank_widget.click()
        # time.sleep(0.5)
        if poco(text="更多信息").exists():
            poco(text="更多信息").click()
            # time.sleep(0.5)
        view_widget_list = poco("allCard").child("android.view.View")
        print("num of products:%d" % (len(view_widget_list) - 2))
        i=1
        product_info_list=[]
        while i<len(view_widget_list) - 1:
            bank_widget.click()
            # time.sleep(0.5)
            if poco(text="更多信息").exists():
                poco(text="更多信息").click()
                # time.sleep(0.5)
            view_widget_list = poco("allCard").child("android.view.View")
            # poco("allCard").child("android.view.View").invalidate()
            # view_widget_list = poco("allCard").child("android.view.View")
            product_widget = view_widget_list[i]
            try:
                while product_widget.attr("pos")[1] > 0.8:
                    poco.swipe([0.5, 0.7], [0.5, 0.5])
                    view_widget_list = poco("allCard").child("android.view.View")
                    product_widget = view_widget_list[i]
            except IndexError:
                # 优惠产品数量过多，导致滑屏后索引匹配错位，后面剩下的优惠产品通常也是无效的，因此直接忽略
                break
            # product_widget.child("android.view.View").child("android.view.View")[0].invalidate()
            product_name = product_widget.child("android.view.View").child("android.view.View")[0].get_text()
            product_valid_info = product_widget.child("android.view.View").child("android.view.View")[-1].child("android.view.View")[0].get_text()
            print("产品名:" + product_name)
            print("有效时间:" + product_valid_info)`

**Comment by daichengxmu** [comment]
```python
    banks_widget = poco("allCard").child("android.view.View")[0]
    bank_widget_list = banks_widget.child("android.widget.ListView")[0].child("android.view.View")
    num_banks = len(bank_widget_list)
    bank_info_list=[]
    for i in range(num_banks):
        bank_widget = bank_widget_list[i]
        bank_name = bank_widget.child("android.view.View")[0].get_text()
        print("银行:%s" % bank_name)
        if bank_name in {"招行", "交行"}:
            print("跳过")
            continue
        bank_widget.click()
        # time.sleep(0.5)
        if poco(text="更多信息").exists():
            poco(text="更多信息").click()
            # time.sleep(0.5)
        view_widget_list = poco("allCard").child("android.view.View")
        print("num of products:%d" % (len(view_widget_list) - 2))
        i=1
        product_info_list=[]
        while i<len(view_widget_list) - 1:
            bank_widget.click()
            # time.sleep(0.5)
            if poco(text="更多信息").exists():
                poco(text="更多信息").click()
                # time.sleep(0.5)
            view_widget_list = poco("allCard").child("android.view.View")
            # poco("allCard").child("android.view.View").invalidate()
            # view_widget_list = poco("allCard").child("android.view.View")
            product_widget = view_widget_list[i]
            try:
                while product_widget.attr("pos")[1] > 0.8:
                    poco.swipe([0.5, 0.7], [0.5, 0.5])
                    view_widget_list = poco("allCard").child("android.view.View")
                    product_widget = view_widget_list[i]
            except IndexError:
                # 优惠产品数量过多，导致滑屏后索引匹配错位，后面剩下的优惠产品通常也是无效的，因此直接忽略
                break
            # product_widget.child("android.view.View").child("android.view.View")[0].invalidate()
            product_name = product_widget.child("android.view.View").child("android.view.View")[0].get_text()
            product_valid_info = product_widget.child("android.view.View").child("android.view.View")[-1].child("android.view.View")[0].get_text()
            print("产品名:" + product_name)
            print("有效时间:" + product_valid_info)
```

**Comment by daichengxmu** [comment]
问题表现在以上代码的product_name中，外层循环第二次打印出来的还是第一个选项卡中对应位置的text

**Comment by yimelia** [comment]
。。。
贴出最小代码即可
有可能需要重新完整地获取一次节点信息，之前保存了一半的poco(xxx)可能会不更新
