### ISSUE TITLE
设备重启，第一次调用脚本，poco出错。第一次之后恢复正常

### ISSUE THREAD

**Issue by wudiluner** [AirtestProject/Poco#371]
**描述问题bug**
linux系统，设备重启后，第一次调用py脚本。poco出错

**相关截图**
![QQ截图20200403175313](https://user-images.githubusercontent.com/19303212/78348278-55ba2300-75d4-11ea-9894-e74b3a7e6aa4.png)
![QQ截图20200403175335](https://user-images.githubusercontent.com/19303212/78348300-6074b800-75d4-11ea-9de6-295925f48f70.png)

python 版本: 3.6.8
poco 版本: 1.0.79
airtest 版本: 1.1.3

**设备:**
 - 型号: [Redmi Note 8]
 - 系统: [Android 9]

**其他相关环境信息**
(其他运行环境，例如在CentOS Linux release 7.7.1908 (Core)上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
不清楚具体问题的情况，如果是指在脚本运行过程中，用代码重启了设备的话，poco是不会自动重连的，所以会失败。
建议补充完整问题描述。

**Comment by wudiluner** [comment]
感谢回复。已经找到原因。Android手机断电关机，上电重启后，minicap.py中install_or_upgrade方法中LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1，无法获取version。然后卸载minicap，rm /data/local/tmp/minicap*，但是/data/local/tmp下有一个minicap-images是文件夹，导致出现了上面的问题。

**Comment by yimelia** [comment]
明白了，如果同时使用了原版的minicap文件的话，会和airtest用的稍微有点冲突，但是因为airtest的minicap文件是在原版基础上新增了一点功能，所以建议直接用airtest那个minicap文件即可
