### ISSUE TITLE
如何干净的卸载airtest

### ISSUE THREAD

**Issue by zkdsygwddllwlxj** [AirtestProject/Poco#372]
我需要干净的卸载airtest，之前也没安装，只是运行了解压后的文件，但是我发现运行中，它在其他目录生成了文件，所以，我希望得到官方的关于如何干净卸载该软件的说明。

**Comment by yimelia** [comment]
启动时有一条log，类似于：
```
loading config from : ['C:\\Users\\xxx\\AppData\\Local\\AirtestIDE\\AirtestIDE\\user.json']
```
可以去到这个目录下删除掉这个AirtestIDE的目录，里面包括了配置文件、可能的log文件等。
如果你自己在IDE中设置了自定义的log路径，就需要再另外删除你自行定义的log目录下的文件
