### ISSUE TITLE
unity官方实例rollaball做测试发现的问题

### ISSUE THREAD

**Issue by drakedoglife** [AirtestProject/Poco#4]
打开unity官方实例roll a ball，将unity3d sdk导入，挂载pocomanager于ground对象上，然后打apk包，安装至手机。打开aittest，选择unity，发现左侧poco辅助窗没有将原本所有的ui树遍历出来。比如，player对象，或是本能展开的节点也不能展开了。

**Comment by adolli** [comment]
此问题已修复，请从此[poco-sdk](https://github.com/AirtestProject/Poco-SDK) clone最新版的代码。

测试版本
* Unity: 2017.4.0f1
* poco-sdk: Unity3D versionCode=2
* roll a ball: 1.2

![image](https://user-images.githubusercontent.com/8390109/37950407-f3dd5fb6-31ca-11e8-8ed5-5e302e68b288.png)
