### ISSUE TITLE
Android、IOS、微信小程序跨平台问题

### ISSUE THREAD

**Issue by bbll29** [AirtestProject/Poco#404]
能否支持跨平台开发呢？就是一套代码，同时能运行在Android、IOS、微信小程序，这样能便利很多。目前我看你们的文档都是单端独自开发的。谢谢

**Comment by yimelia** [comment]
airtest可以，也就是截图的话，注意图片截取的兼容性之后，是可以的。
poco的话，由于每一个端开发出来的app，UI结构与命名不一定完全一致，因此不支持。
