### ISSUE TITLE
有时候识别不到所有元素

### ISSUE THREAD

**Issue by imhsz** [AirtestProject/Poco#405]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

偶发,poco识别不到整个控件树,如图所示
![image](https://user-images.githubusercontent.com/3312454/90091310-98e18b00-dd58-11ea-98aa-6cd7836f405b.png)
具体代码(任意代码都可能复现,以下是精简代码):
```
from airtest.core.api import *

from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)

def PocoExists(pocoItem):
    print('pocoQuery:%s'%pocoItem)
    btnPoco = pocoItem
    if not pocoItem:
        print('not:%s'%pocoItem)
        return False
    print('pocoExists:%s'%pocoItem.exists())    
    pos = pocoItem.get_position()
    print('pocoPos:%s'%pocoItem.get_position())
    return pocoItem.exists() and (0 <= pos[0] <= 1) and (0 <= pos[1] <= 1)


print(PocoExists(poco('android.widget.FrameLayout')))
```

**复现步骤**
1. airtest 点击运行
2. 输出结果

**预期效果**
应该是要打印true

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![image](https://user-images.githubusercontent.com/3312454/90091310-98e18b00-dd58-11ea-98aa-6cd7836f405b.png)

**python 版本:** `python3.6`

**poco 版本:** `1.0.79`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: 华为 lon-al00
 - 系统: Android 7.1
 - (别的信息)

**其他相关环境信息**
window 10和 centos 都出现过

**Comment by imhsz** [comment]
补充:在手机上任意滑动下就认到了

**Comment by yimelia** [comment]
直接用`.exists()`来判断是否存在，if poco(xxx)基本上没有意义。

**Comment by imhsz** [comment]
确认.exists();但是之前加if poco(xxx) 判断,是因为真的没有这个元素时,直接exists会异常:
![image](https://user-images.githubusercontent.com/3312454/90093910-350e9080-dd5f-11ea-8779-a4091528567d.png)

**Comment by imhsz** [comment]
exists 不会异常,我其他代码导致.此单关闭.谢谢@yimelia
