### ISSUE TITLE
UnityPoco(unity_editor=True) 会报错

### ISSUE THREAD

**Issue by magicedy** [AirtestProject/Poco#41]
如果用UnityPoco(unity_editor=True)，会报错pywinauto.findwindows.ElementNotFoundError: {'class_name': 'UnityWndClass', 'title_re': 'Unity.*', 'backend': 'win32'}

poco/drivers/unity3d/unity3d_poco.py

    def __init__(self, addr=DEFAULT_ADDR, unity_editor=False, connect_default_device=True, **options):
        if 'action_interval' not in options:
            options['action_interval'] = 0.5

        dev = None
        if unity_editor:
            dev = connect_device("Windows:///?class_name=UnityWndClass&title_re=Unity.*")
            game_window = dev.app.top_window().child_window(title="UnityEditor.GameView")
            dev._top_window = game_window.wrapper_object()
            dev.focus_rect = (0, 40, 0, 0)

Unity editor的window class应该是 "UnityContainerWndClass"
Unity player (a Unity build game) 的window class才是 "UnityWndClass"

**Comment by adolli** [comment]
多谢反馈，我验证一下这个问题。

**Comment by magicedy** [comment]
@adolli Unity537

**Comment by adolli** [comment]
验证过确实是class name搞错了。fixed. 如果使用AirtestIDE开发的话，需要等下周版本放出，如果使用源码或python lib，可以直接`pip install -U pocoui`进行更新。

**Comment by quaerere** [comment]
发现最新的还是会报错pywinauto.findwindows.ElementNotFoundError: {'class_name': 'UnityContainerWndClass', 'title_re': 'Unity.*', 'backend': 'win32'}

**Comment by LacusCon** [comment]
修改这个poco/drivers/unity3d/device.py
dev = connect_device("Windows:///?class_name=UnityContainerWndClass&title_re=.*Unity.*")
