### ISSUE TITLE
Poco录制脚本问题

### ISSUE THREAD

**Issue by uplk** [AirtestProject/Poco#446]
**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
如图，点击红框返回按钮，Poco录制时候不会生成代码，但是手机确实会返回
![QQ图片20210322152839](https://user-images.githubusercontent.com/59159115/111962737-a69c9180-8b2d-11eb-9747-682166fe80e9.png)

**预期效果**
(预期想要得到什么、见到什么)
Poco录制脚本时候，点击底部返回，Home键可以自动生成代码

**python 版本:** `python3.8`

**poco 版本:** 
> poco版本通过`pip freeze`可以命令可以查到
输入命令没找到
下载的压缩包是AirtestIDE-win-1.2.8.zip

**设备:**
 - 型号: [e.g. SM-G6200]
 - 系统: [e.g. Android 8.1]

**Comment by yimelia** [comment]
这个是系统按钮，不是手机里某个软件界面的按钮，因此无法捕捉到
