### ISSUE TITLE
pycharm调试airtest脚本的时候一直报错，提示缺少android-11

### ISSUE THREAD

**Issue by ArielDing** [AirtestProject/Poco#454]
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'C:\\........\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-11/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']

**Comment by yimelia** [comment]
你本地环境的airtest版本号是多少？升级到最新版再试试

**Comment by yimelia** [comment]
还有就是你手机使用的android版本号是多少？
