### ISSUE TITLE
unity 项目集成pocosdk之后，在手机上运行报错：[WinError 10053] 你的主机中的软件中止了一个已建立的连接。

### ISSUE THREAD

**Issue by jihuer** [AirtestProject/Poco#455]
ide 版本：1.2.8
运行到手机上，执行到poco的命令时就报错:
![image](https://user-images.githubusercontent.com/28520781/115982523-7a61ae00-a5ce-11eb-8052-711290991a22.png)
unity 版本是2018.4.21
测试手机是华为p30,和小米9 Android10版本

**Comment by yimelia** [comment]
先启动游戏再初始化poco
