### ISSUE TITLE
是否支持webview，如何切换

### ISSUE THREAD

**Issue by XedGo** [AirtestProject/Poco#49]
最近在学习poco框架，提的问题有点多~~~

**Comment by adolli** [comment]
webview是否能用取决于承载webview的浏览器内核组件，不同平台上的webview有点不一样，android的话需要在开发者选项里将webview设置为chrome内核（如果有该设置的话）。另外你可以在AirtestIDE里的Poco辅助面板中切换到Android模式，看下webview的结构是否能刷出来。

**Comment by adolli** [comment]
你们应用大概是一个怎么样的应用？

**Comment by XedGo** [comment]
@adolli https://xunbug.com/airtestpeoject-poco-webview.html  我这样干的~~

**Comment by lycfr** [comment]
@adolli 这个除了支持chrome内核的webview外，还支持其他的吗？比如腾讯的X5内核webview

**Comment by adolli** [comment]
@lycfr 腾讯X5内核是他们私有的自研内核，官方文档中说的是做了大量优化，因此accessibility相关的实现也是被移除的了。如果需要支持可能有以下的方式
* X5内置实现accessibility接口（需要腾讯支持，不太可能实现）
* 页面注入poco-sdk-js（还在研究如何注入，注入后将与Android native app分离，独立展示Hierarchy）
其余的浏览器内核的情况类似。

**Comment by test-h** [comment]
代码中怎么切换到webview

**Comment by yimelia** [comment]
可以参考文档 http://airtest.netease.com/docs/cn/6_poco_framework/poco_webview.html
