### ISSUE TITLE
connect error

### ISSUE THREAD

**Issue by drakedoglife** [AirtestProject/Poco#5]
I used adb forward to connect but it just told me 'no module named drivers.unity3d'
I've upgraded poco and pocoui already.
Still let me upgrade.
![image](https://user-images.githubusercontent.com/37531000/37815022-1a5ea058-2ea8-11e8-8f6a-1978b2f00603.png)

**Comment by adolli** [comment]
I am sorry for the wrong toast tips. It should be `pip install pocoui --upgrade` not poco. If you have already installed poco, please uninstall it with `pip uninstall poco` and reinstall pocoui with `pip install pocoui`. Then restart the HierarchyViewer.
