### ISSUE TITLE
在Intellijj idea 执行poco的指令，会不停的有adb.exe弹窗闪烁

### ISSUE THREAD

**Issue by chely12345** [AirtestProject/Poco#50]
应该是执行了adb.exe -s 127.0.0.1:7555 shell 导致的，脚本可以正常运行但体验不是很好。

**Comment by adolli** [comment]
这个问题估计是IntelliJ调用subprocess的时候用的是shell模式，你看下IntelliJ里能不能设置

**Comment by chely12345** [comment]
虽然没解决，但发现在PyCharm中运行不会有这个问题。   
还想问一个问题，安卓原生应用中的 H5页面 要怎样获得UI结构树，目前似乎只能显示文本.

**Comment by adolli** [comment]
H5页面取决于对应的webview实现，如果这个webview组件没有实现标准的accessibility标准的话，确实是没法获取内部的细节的。
