### ISSUE TITLE
Win10 无法链接到Windows窗口

### ISSUE THREAD

**Issue by chely12345** [AirtestProject/Poco#51]
无论是选定窗口 还是 搜索窗口，选定后 “设备窗” 都会自动关闭。
![image](https://user-images.githubusercontent.com/39823473/43138930-f78b530a-8f82-11e8-9bed-51bb873c2e34.png)

**Comment by yimelia** [comment]
@chely12345 有些窗口可能在嵌入时会发生一些不可预期的问题，可以尝试下这个 [无嵌入方案](http://airtest.netease.com/docs/cn/2_device_connection/5_windows_connection.html#id2) 看看
