### ISSUE TITLE
无法获取Root节点的子节点

### ISSUE THREAD

**Issue by NiceTestMan** [AirtestProject/Poco#519]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
我想获取所有节点，打算从Root节点遍历至尾节点，发现无法获取Root节点的子节点
![image](https://user-images.githubusercontent.com/50130180/150294307-f047400b-6575-47a2-8436-34fc259c50cd.png)
![image](https://user-images.githubusercontent.com/50130180/150294577-4644f722-2287-4b71-bbab-028a5a398944.png)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\poco\proxy.py", line 233, in __getitem__
    nodes = self._do_query(multiple=True, refresh=True)
  File "D:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\poco\proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "<Root>/"
```
（在这里粘贴traceback或其他报错信息）
```

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python3.9.9`

**poco 版本:** `1.0.85`

**设备:**
 - 型号: [e.g. XiaoMI 11]
 - 系统: [e.g. Android 12]
 - (别的信息)

**Comment by yimelia** [comment]
不能这样写，因为这个<ROOT>节点是为了显示方便额外加上去的虚拟节点，实际上不存在一个叫做<ROOT>的节点。。。
ROOT下面那个3个节点，每一个实际上都是真正的根节点，这3个节点之间是没有关联的。

**Comment by NiceTestMan** [comment]
> 

可以让其变为一个实际的节点吗？代表整个屏幕
![image](https://user-images.githubusercontent.com/50130180/150311952-23acfa01-4774-4114-9fe3-91105bae94c0.png)
