### ISSUE TITLE
mac系统进行Android ui自动化 ，多条例执行时会发生崩溃

### ISSUE THREAD

**Issue by dxc19951001** [AirtestProject/Poco#552]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
大概左右30条case进行自动化执行，在执行到50%以后会报错
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
poco所有权限都已经开启了

```
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\nINSTRUMENTATION_CODE: 0\n'
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 [pocoservice.apk] stdout: b''
16:21:09 [pocoservice.apk] stderr: b''
16:21:09 still waiting for uiautomation ready.
16:21:09 still waiting for uiautomation ready.
16:21:09 still waiting for uiautomation ready.
16:21:09 still waiting for uiautomation ready.
16:21:09 still waiting for uiautomation ready.
```

**复现步骤**
1.基于pytest和airtest编写Android端的ui自动化
2.编写case超过30条
3.进行批量
4.执行至50%以后会出现crash报错，poco所有权限都已经开启

**预期效果**
执行多条case，能够正常执行

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `3.8.12`

**poco 版本:** `1.0.85`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: 小米11
  - 系统: Android 10
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/poco_framework/7_poco_restart/
