### ISSUE TITLE
No matching distribution found for  opencv-contrib-python==3.2.0.7 (from airtest- >pocoui)

### ISSUE THREAD

**Issue by gfollower** [AirtestProject/Poco#56]
无法使用python3.7命令pip install pocoui安装依赖库

**Comment by adolli** [comment]
python3.7太新了，很多依赖库还不支持，请先不要使用超过3.6的版本。

**Comment by gfollower** [comment]
重装python3.6后可以安装pocoui了，但是无法用pycharm跑通Airtest生成的py文件，设备上无法实现swipe操作

**Comment by adolli** [comment]
https://github.com/AirtestProject/AirtestIDE/issues/208
