### ISSUE TITLE
Poco UIProxyObject的方法高频调用的时候，RPC 发到手机端的json 末尾会有奇怪的字符导致无法解析。

### ISSUE THREAD

**Issue by kaluluosi** [AirtestProject/Poco#6]
![image](https://user-images.githubusercontent.com/1620585/37945202-a59c35ac-31b1-11e8-9677-438dc0d746bc.png)
![image](https://user-images.githubusercontent.com/1620585/37945210-affdb11a-31b1-11e8-8497-7fe023af30e6.png)

Poco UIProxyObject的方法连续调用（无sleep，无间隔），RPC 发到手机端的json 末尾会有奇怪的字符导致无法解析。

**Comment by kaluluosi** [comment]
![image](https://user-images.githubusercontent.com/1620585/37948379-7eb0c5fa-31c2-11e8-9077-7e3398767c7b.png)

应该是只有Unity的SDK才有这个问题。
怀疑是SimpleProtocolFilter里解包处理时，offset有1个字符的误差。

**Comment by adolli** [comment]
fixed at https://github.com/AirtestProject/Poco-SDK/commit/f73f59e38b47f9dfb956f6509c04b77c308da226. Thanks @kaluluosi !
