### ISSUE TITLE
HarmonyOS执行多次代码片段崩溃

### ISSUE THREAD

**Issue by luowqn** [AirtestProject/Poco#603]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
连续多次执行相同代码片段（上传图片），执行过程中可能会强制停止再执行，一段时间后出现pocservice.apk崩溃

**复现步骤**
1. 定位上传图片控件列表
2. 执行滚动条滑动
3. 逐个控件上传图片
4. 判断是否到底部，上传图片是否已完成，未完成，重复执行以上3个步骤
或者
1、有时候任意下执行代码片段一段时间后也会出现，出现概率较小
**预期效果**
能持续完成这些操作

**相关截图**
![image](https://github.com/AirtestProject/Poco/assets/20413980/535ea7c5-d976-4ea9-9a50-5178792d4ec7)

**python 版本:** `python3.11.0`

![image](https://github.com/AirtestProject/Poco/assets/20413980/7389702d-6a8b-42c3-90df-48b6fb6045da)
**设备:**
 - 型号: [华为P20]
 - 系统: [HarmonyOS 3.0.0]

**其他相关环境信息**
在HP ProBook Windows11家庭中文版运行
airtestIDE：1.2.6

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/poco_framework/7_poco_restart/
试着改一下这个设置看看

**Comment by luowqn** [comment]
已根据所有权限设置，仍然出现次问题
