### ISSUE TITLE
cocos2dx-lua项目没有启用 socket 或 socket.core 模块

### ISSUE THREAD

**Issue by Danieltdd** [AirtestProject/Poco#61]
我的cocos2dx-lua项目没有启用 socket 或 socket.core 模块，该怎么初始化poco服务呢？

**Comment by Danieltdd** [comment]
自答，没法

**Comment by adolli** [comment]
@Danieltdd 可以让你们程序加上luasocket这个模块，已经是cocos2dx的标准模块之一了。或者你们用的是其他的网络库？
