### ISSUE TITLE
小米5s、HTC2Q4R400等手机不能正常获取控件名称

### ISSUE THREAD

**Issue by wcp1234** [AirtestProject/Poco#63]
ZTEA3、华为P9手机可以通过poco正常获取控件属性，但小米5s、HTC2Q4R400两款手机获取的控件名称为空，是分辨率问题吗？有没有什么办法解决呢

**Comment by adolli** [comment]
名称为空应该不是分辨率问题，试试打开开发者选项里的“查看视图布局/属性”这个选项

**Comment by wcp1234** [comment]
果然是这个原因，试了小米5s，勾选掉“启用视图属性检查功能”就可以正常获取控件属性了，感谢@adolli
