### ISSUE TITLE
Linux下脚本无法运行

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Poco#66]
![image](https://user-images.githubusercontent.com/29672247/43821553-175c4884-9b1c-11e8-8034-2b8da3bd8787.png)

**Comment by lycfr** [comment]
我这边adb是改了Linux系统默认的路径，运行后就报错了

**Comment by lycfr** [comment]
已解决。不好意思

**Comment by Meteorix** [comment]
@lycfr 你好，可以说一下解决办法吗

**Comment by lycfr** [comment]
@Meteorix 我解决的方法很简单，就直接把adb直接更新了一下，就可以用了

**Comment by lycfr** [comment]
@Meteorix 我碰到一个问题，我在1920*1080上用IDE截图及运行的case，然后换台1080*2160的手机去跑，发现脚本没有异常，但是运行一会就中断（用的是指令运行脚本，但是IDE运行时正常通过），没报任何错误。（同一分辨率运行也是没问题的）
我的代码也加入了
`def custom_resize_method(w, h, sch_resolution, src_resolution):
    print(w, h, sch_resolution, src_resolution)
    return int(w), int(h)
ST.RESIZE_METHOD = custom_resize_method`
你可以看一下我运行的结果报告
[对比报告.zip](https://github.com/AirtestProject/Poco/files/2272618/default.zip)

**Comment by Meteorix** [comment]
你好，感谢反馈。后面一个问题新开issue吧，请贴上控制台的log。
