### ISSUE TITLE
电脑系统：windows 64位

### ISSUE THREAD

**Issue by CRwangzhen** [AirtestProject/Poco#72]
Remove any following parts if does not have details about

**Describe the bug**
A clear and concise description of what the bug is. Or paste traceback below.

```
paste traceback here
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**python version:** `python2.7`

**poco version:** `1.0.69`
> You can get poco version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by yimelia** [comment]
请描述清楚你的问题，非常感谢

**Comment by CRwangzhen** [comment]
电脑设备系统：windows7  64位
问题描述：

1. 只要将录制好的脚本保存之后，脚本编辑窗就不在显示任何信息，新建脚本也是一样不在显示任何信息；
![image](https://user-images.githubusercontent.com/42568409/44395134-81a5a380-a56b-11e8-92f6-9b1a0f7b5a8f.png)

2、保存好的脚本也不能再打开重复利用，保存好的py格式脚本内存为0——————》》
![image](https://user-images.githubusercontent.com/42568409/44394487-e2cc7780-a569-11e8-932b-576cde0669c4.png)

**Comment by CRwangzhen** [comment]
这样的话脚本就没办法保存重复利用了

**Comment by CRwangzhen** [comment]
而且也不能正常的新建脚本编译

**Comment by yimelia** [comment]
@CRwangzhen 这边是Poco的仓库，可以把这个问题提到 AirtestIDE的[issue](https://github.com/AirtestProject/AirtestIDE/issues)页面，并且最好贴一下在发生报错的时候（或者刚启动IDE之后也可以的），另外那个IDE的黑色命令行终端里的log内容
