### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by StandOutstar** [AirtestProject/Poco#78]
**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![image](https://user-images.githubusercontent.com/17442044/44850663-89162c80-ac90-11e8-9ec3-33c0add2fc86.png)
不知这里为什么获取二进制字符串？

**Comment by adolli** [comment]
此为py3中的bug，我们在下个本版本会修复这个兼容性问题。

**Comment by adolli** [comment]
fixed. AirtestIDE里会在下一个版本中更新。有疑问随时reopen issue。
