### ISSUE TITLE
操作UI的Click和Focus函数在调试Win下的Unity游戏会报错

### ISSUE THREAD

**Issue by zxc3246183** [AirtestProject/Poco#79]
环境是Win平台，使用Poco调试Unity游戏
在我的游戏中，有一个按钮的锚点坐标是[0.5, 0]，在直接使用poco("xxx").click()的情况下，脚本会点击该UI元素上方的某一个位置而不会点击到UI检测区域内（点击坐标异常），为此我尝试使用了click([0.5, 0.5])与focus([0.5, 0.5]).click()，但二者均会报一下错误提示：
![image](https://user-images.githubusercontent.com/12513067/45139410-400b2e80-b1e2-11e8-94c8-9ae5a1249be1.png)

**Comment by zxc3246183** [comment]
![image](https://user-images.githubusercontent.com/12513067/45727004-6b374a00-bbf4-11e8-869b-c5c5f8044a21.png)

**Comment by adolli** [comment]
![image](https://user-images.githubusercontent.com/8390109/45999765-37b75c80-c0d9-11e8-9c61-bebca8da5894.png)

**Comment by zxc3246183** [comment]
![image](https://user-images.githubusercontent.com/12513067/46000040-0be8a680-c0da-11e8-9fa7-eb5935ffbba9.png)

**Comment by adolli** [comment]
看来像size属性获取错误了，请问你用的是ugui还是ngui？
![image](https://user-images.githubusercontent.com/8390109/46000094-35093700-c0da-11e8-996b-0cbadb81e84a.png)

**Comment by zxc3246183** [comment]
ugui

**Comment by adolli** [comment]
请问是所有的控件都是这样的size吗

**Comment by zxc3246183** [comment]
大部分都是，有少部分正常

**Comment by adolli** [comment]
请问Canvas这个gameObject里RenderMode是哪种？`ScreenSpaceCamera`/`WorldSpace`/`其他` 。顺便贴一下UnityEditor里Canvas的Inspector面板里的属性

**Comment by zxc3246183** [comment]
WorldSpace
![image](https://user-images.githubusercontent.com/12513067/46000553-80701500-c0db-11e8-94e9-7544a84c000e.png)

**Comment by adolli** [comment]
因为WordSpace下，size是通过Canvas的size来计算的，这里可以修改成你们的UI设计分辨率吗？一般来说不影响显示效果。
![image](https://user-images.githubusercontent.com/8390109/46000642-bb724880-c0db-11e8-8110-227ed88bf844.png)

**Comment by zxc3246183** [comment]
好，我重新打个包试试

**Comment by adolli** [comment]
目前没有，目前自动通过Canvas RectTransform的size来计算尺寸。你也可以适当修改sdk代码，将CanvasWidth和CanvasHeight通过PocoManager的public成员传进去。
