### ISSUE TITLE
oppo r15 8.1.0使用ide无法运行代码

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Poco#84]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
![image](https://user-images.githubusercontent.com/29672247/45857428-301b4f00-bd8b-11e8-82fb-7ee609a35c20.png)

**复现步骤**
1. 直接运行就报错

**预期效果**
不应报错

**相关截图**
![image](https://user-images.githubusercontent.com/29672247/45857445-445f4c00-bd8b-11e8-9be1-85ddf6f886b7.png)

**python 版本:** `python3.6.5`

**poco 版本:** `1.0.69`
>1.0.69

**设备:**
 - 型号: oppo R15
 - 系统: [Android 8.1.0]

**Comment by adolli** [comment]
请问能贴一下你运行的代码吗？包括log面板里的运行命令`.../AirtestIDE runner ...`这一句

**Comment by yimelia** [comment]
可能需要手工安装一下yosemite.apk，可能是因为不输入密码不能替换掉旧的yosemite包，导致启动poco也跟着失败

**Comment by yimelia** [comment]
@lycfr 我们这里试过，有可能因为没有输入密码导致无法通过USB自动安装apk，因此连带无法使用poco，可以查看IDE目录下的`AirtestIDE\airtest\core\android\static\apks` 里，手工将 `Yosemite.apk` 安装到你的手机中，然后再尝试。有可能也需要手工安装 `AirtestIDE\poco\drivers\android\lib` 里的2个apk。我之前试过这台手机手工安装过yosemite后就可以启动了，可以试试看。如果需要更多帮助，请reopen这个issue，非常感谢
