### ISSUE TITLE
使用另一个Python脚本subprocess调用测试脚本时会一直卡住红色Yosemite界面

### ISSUE THREAD

**Issue by laihanhua** [AirtestProject/Poco#91]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

使用另一个Python脚本subprocess调用测试脚本时会一直卡住红色Yosemite界面，并且没有任何logger提示。

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by zzldjkzxf** [comment]
@laihanhua  你好，我在本地用subprocess调用另一个脚本是正常的。可以麻烦你把你具体调用的代码发一下吗，还有设备信号。方便我们帮你定位问题，谢谢！
