### ISSUE TITLE
我想问下能不能自行设置跑测试脚本的返回码

### ISSUE THREAD

**Issue by laihanhua** [AirtestProject/Poco#92]
我想问下能不能自行设置跑测试脚本的返回码，例如我用另一个脚本通过subprocess来调用测试脚本，如果脚本某一个案例失败返回-1，全部通过返回0。目前好像不管什么情况返回值都为0.(popen.returncode)

**Comment by Meteorix** [comment]
你是用airtest的命令行运行的吗？

**Comment by laihanhua** [comment]
@Meteorix 不是，我是自己写py文件，调用airtest.corp,poco,等库，类似于Unittest单元测试。然后用另一个脚本来执行，需要对测试的结果返回不同的返回码。

**Comment by Meteorix** [comment]
那就是python的返回值问题了，如果是raise出来的报错，exit code是1
