### ISSUE TITLE
出现这个之后airtest就不能正常点击屏幕了  orientationWatcher has ended

### ISSUE THREAD

**Issue by silencesmile** [AirtestProject/Poco#96]
![image](https://user-images.githubusercontent.com/11863270/47333731-99f28580-d6b6-11e8-9bcc-d8fd45b2f3f7.png)

一出现这个，airtest的点击就会失败，什么操作会出现这个？怎么解决，  我是在截取手机屏幕图片时，引起的，但我在该文件之前的代码中也用了同样的截图，并没有什么影响。

airtest：1.0.23
pocoui：1.0.70
python：3.6.5
安卓真机：红米note3  系统：5.1.1

**Comment by yimelia** [comment]
不要同时开启其他的手机助手，或是同时使用adb操作，可能会导致airtest的adb断开。在执行脚本、连接手机时务必确保机器上所有手机助手类软件都退出，并且不要抢占ADB，小米手机需要同时开启手机设置里的允许模拟点击选项，理论上照这样做就不会有问题的。

这个问题属于airtest仓库，如果还需要任何帮助，请发Issue到[airtest](https://github.com/AirtestProject/Airtest/issues)

**Comment by silencesmile** [comment]
请问我在出现adb断开之后，又重新建立airtest连接，为什么还是不能继续使用




| |
henan_youngstar
|
|
henan_youngstar@163.com
|
签名由网易邮箱大师定制


在2018年10月23日 11:41，yimelia<notifications@github.com> 写道：

不要同时开启其他的手机助手，或是同时使用adb操作，可能会导致airtest的adb断开。在执行脚本、连接手机时务必确保机器上所有手机助手类软件都退出，并且不要抢占ADB，小米手机需要同时开启手机设置里的允许模拟点击选项，理论上照这样做就不会有问题的。

这个问题属于airtest仓库，如果还需要任何帮助，请发Issue到airtest
